### ISSUE TITLE
空格反白→按tab→空格跑到前面

### ISSUE THREAD

**Issue by lamalien** [karmapa/ketaka-lite#102]
![issue_16112015_4a](https://cloud.githubusercontent.com/assets/5266492/11183953/a9dc82ba-8caf-11e5-9d8c-c8f17658b7b3.png)
![issue_16112015_4b](https://cloud.githubusercontent.com/assets/5266492/11183954/aa1479a4-8caf-11e5-990f-cc41774c5fdd.png)

**Comment by kmsheng** [comment]
@lamalien 這是 codemirror 預設行為, 如果有選取東西時按 tab, 會整行都 indent.
目前我在 v0.1.49 將 indent 行為改成選取時不會整行 indent, 請再測試看看有沒有問題。

另外, indent 字元為了以後跨平台著想, 我改成兩個空白字元了

**Comment by kmsheng** [comment]
![screen shot 2015-12-02 at 5 03 18 pm](https://cloud.githubusercontent.com/assets/880569/11526623/9f7eb07c-9916-11e5-8c18-0ba559b75b4f.png)
