### ISSUE TITLE
Export zip→到mac inport zip→OK 但是工具列變成↓ 還可以選前後頁，之後再重新import幾次都沒有這些問題。

### ISSUE THREAD

**Issue by lamalien** [karmapa/ketaka-lite#103]
![issue_16112015_5a](https://cloud.githubusercontent.com/assets/5266492/11183994/e2ea5816-8caf-11e5-91f7-e2154fdf2aaf.png)

**Comment by kmsheng** [comment]
@lamalien 所以不能穩定重製對嗎 ?

**Comment by kmsheng** [comment]
![screen shot 2015-12-02 at 5 16 41 pm](https://cloud.githubusercontent.com/assets/880569/11526879/7e150236-9918-11e5-8fb8-204d0bf7f174.png)
