### ISSUE TITLE
open "replace" from the navigation bar, "replace" cannot find the matched words

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#105]
tested in windows v0.1.50
1. close and re-open ketaka-lite (bug only shows in the first time replacing when re-opening ketaka-lite)
2. use "replace" from navigation bar (don't use hotkeys, there is no bug using "replace" from hotkeys )
![editreplace2](https://cloud.githubusercontent.com/assets/13195099/11330652/a524f3bc-91e9-11e5-9ec0-22ca4ee72d5b.jpg)
3. "1" should be highlighted and show the matched number in the input column
![editreplace3](https://cloud.githubusercontent.com/assets/13195099/11330653/a6f0856c-91e9-11e5-95f9-83ee1257be3b.jpg)

**Comment by kmsheng** [comment]
fixed in v0.1.52
