### ISSUE TITLE
One "undo" cancels several typed letters or lines in Mac version

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#107]
In Mac version 0.1.50, 
if not typing very slowly, one "undo" won't only cancel one letter, it may cancel several letters or lines once.

**Comment by kmsheng** [comment]
@chiehan1 History event delay can be adjusted if this is the issue.
http://codemirror.net/3/doc/manual.html

```
historyEventDelay: integer
The period of inactivity (in milliseconds) that will cause a new history event to be started
 when typing or deleting. Defaults to 500.
```

**Comment by kmsheng** [comment]
![screen shot 2015-12-02 at 5 14 29 pm](https://cloud.githubusercontent.com/assets/880569/11526837/35c48e66-9918-11e5-8a71-d75c03745275.png)
