### ISSUE TITLE
Select-all of navigation bar doesn't work

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#108]
In v0.1.50 in windows and mac,
click select-all of navigation bar, but it doesn't work.
![selectall](https://cloud.githubusercontent.com/assets/13195099/11417041/3d1f886a-944e-11e5-8079-b515ef9911d3.jpg)

**Comment by kmsheng** [comment]
Reported to electron
https://github.com/atom/electron/issues/3592

**Comment by kmsheng** [comment]
fixed in v0.1.57

**Comment by chiehan1** [comment]
Test ok!
Thank you!!!
