### ISSUE TITLE
After highlighting, changing font size, then click the highlighted area, the toolbar will disappear.

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#109]
In mac and windows v0.1.54
1. Change the direction mode as the picture, set the font size to 1, add 40 lines around, then use mouse to hightlight it.
![toolbar1](https://cloud.githubusercontent.com/assets/13195099/11463767/f31bb40c-9761-11e5-9b87-f6c3c99d6c9f.JPG)
2. Set the font size to 30.
![toolbar2](https://cloud.githubusercontent.com/assets/13195099/11463769/f4cb2242-9761-11e5-98bb-98ca6a636a35.jpg)

![toolbar3](https://cloud.githubusercontent.com/assets/13195099/11463770/f654ffa2-9761-11e5-8221-010963b797dd.jpg)
3. Use mouse to click the highlighted area, then (a) toolbar disappear, (b) there is an empty space showing up at the bottom.
![toolbar4](https://cloud.githubusercontent.com/assets/13195099/11463771/f8227698-9761-11e5-84b9-9fec7e9d1216.jpg)
4. Ctrl + f to call the search bar, the toolbar shows up, and the bottom empty space disappears to normal.
![toolbar5](https://cloud.githubusercontent.com/assets/13195099/11463772/fa1768a0-9761-11e5-9e9e-1aafe742777f.JPG)

**Comment by kmsheng** [comment]
@chiehan1 我測過 0.1.64 沒這問題耶 ? 請捷安看看

**Comment by chiehan1** [comment]
對， 0.1.64 沒這問題耶
