### ISSUE TITLE
spellcheck檢查到錯字後，會連正確字裡的該字元一起highlight

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#110]
KETAKA-Lite v0.1.57 win8

把行距調到5

測試文本如下
ཚོགས་དང་། རྟ་པའི་ཚོགས་དང་། ཤིང་རྟ་པའི་ཚོགས་དང་། དཔུང་བུ་ཆུང་གི་ཚོགས་གོ་བསྐོན་ཏེ། ཡུལ་ཨང་ག་ཙམ་པ་མ་གཏོགས་པ་བཅོམ་ནས་ཕྱིར་ལྡོག་པར་བྱེད་དོ། །དེ་ནས་དུས་གཞན་ཞིག་ན་ཨང་
གའི་རྒྱལ་པོ་དཔུང་དང་མཐུ་ཆེ་བར་གྱུར་ནས་དེས་དཔུང་གི་ཚོགས་ཡན་ལག་བཞི་པ་གླང་པོ་ཆེ་པའི་ཚོགས་དང་། རྟ་པའི་ཚོགས་དང་། ཤིང་རྟ་པའི་ཚོགས་དང་། དཔུང་བུ་ཆུང་གི་ཚོགས་གོ་བསྐོན་ཏེ་ཡུལ་མ་
ག་དྷ་གཞོམ་པར་བརྩམས་པ་དང་། མ་ག་དྷ་ན་གནས་པའི་སྐྱེ་བོའི་ཚོགས་ཀྱིས་རྒྱལ་པོ་པད་མ་ཆེན་པོ་ལ་ལྷ་ཨང་གའི་རྒྱལ་པོས་དཔུང་གི་ཚོགས་ཡན་ལག་བཞི་པ་གླང་པོ་ཆེ་པའི་ཚོགས་དང་། 
རྟ་པའི་ཚོགས་དང་། ཤིང་རྟ་པའི་ཚོགས་དང་། དཔུང་བུ་ཆུང་གི་ཚོགས་གོ་བསྐོན་ཏེ་ཡུལ་མ་ག་དྷ་འཇོམས་པར་བགྱིད་དོ་ཞེས་སྦྲོན་པ་དག་བཏང་ངོ་། །རྒྱལ་པོ་པད་མ་ཆེན་པོས་ཀྱང་ཐོས་ནས་དཔུང་གི་

**正常情形**
spellcheck後如下圖，找到三個錯字
![spellcheckhighlight1](https://cloud.githubusercontent.com/assets/13195099/12028666/f289449e-ae15-11e5-8212-051c70181018.JPG)

用 https://github.com/karmapa/checkTibetan_for_ketaka 跑出來的結果是
[ [ 332, 2, 'དྷ' ],
  [ 360, 2, 'དྷ' ],
  [ 563, 2, 'དྷ' ] ]

**錯誤情形**
單獨存在的 ོ是錯字
在文本最後面加上一個錯字 ོ

ཚོགས་དང་། རྟ་པའི་ཚོགས་དང་། ཤིང་རྟ་པའི་ཚོགས་དང་། དཔུང་བུ་ཆུང་གི་ཚོགས་གོ་བསྐོན་ཏེ། ཡུལ་ཨང་ག་ཙམ་པ་མ་གཏོགས་པ་བཅོམ་ནས་ཕྱིར་ལྡོག་པར་བྱེད་དོ། །དེ་ནས་དུས་གཞན་ཞིག་ན་ཨང་
གའི་རྒྱལ་པོ་དཔུང་དང་མཐུ་ཆེ་བར་གྱུར་ནས་དེས་དཔུང་གི་ཚོགས་ཡན་ལག་བཞི་པ་གླང་པོ་ཆེ་པའི་ཚོགས་དང་། རྟ་པའི་ཚོགས་དང་། ཤིང་རྟ་པའི་ཚོགས་དང་། དཔུང་བུ་ཆུང་གི་ཚོགས་གོ་བསྐོན་ཏེ་ཡུལ་མ་
ག་དྷ་གཞོམ་པར་བརྩམས་པ་དང་། མ་ག་དྷ་ན་གནས་པའི་སྐྱེ་བོའི་ཚོགས་ཀྱིས་རྒྱལ་པོ་པད་མ་ཆེན་པོ་ལ་ལྷ་ཨང་གའི་རྒྱལ་པོས་དཔུང་གི་ཚོགས་ཡན་ལག་བཞི་པ་གླང་པོ་ཆེ་པའི་ཚོགས་དང་། 
རྟ་པའི་ཚོགས་དང་། ཤིང་རྟ་པའི་ཚོགས་དང་། དཔུང་བུ་ཆུང་གི་ཚོགས་གོ་བསྐོན་ཏེ་ཡུལ་མ་ག་དྷ་འཇོམས་པར་བགྱིད་དོ་ཞེས་སྦྲོན་པ་དག་བཏང་ངོ་། །རྒྱལ་པོ་པད་མ་ཆེན་པོས་ཀྱང་ཐོས་ནས་དཔུང་གི་
ོ

除了單獨的錯字 ོ，spellchek會標出文章中所有正確字裡的 ོ
如下圖
![spellcheckhighlight2](https://cloud.githubusercontent.com/assets/13195099/12028668/f4d55f80-ae15-11e5-9eab-545b25782c07.JPG)

但是用程式跑出來的結果是正常的，錯字只有4個位置，但KETAKA-Lite會標出所有位置的 ོ
[ [ 332, 2, 'དྷ' ],
  [ 360, 2, 'དྷ' ],
  [ 563, 2, 'དྷ' ],
  [ 651, 1, 'ོ' ] ]

**Comment by kmsheng** [comment]
@chiehan1 已在 v0.1.62 修正

**Comment by chiehan1** [comment]
test ok in v0.1.62
