### ISSUE TITLE
輸入藏文後，navigation bar 的 undo 和 redo 不能還原輸入藏文前的狀態

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#111]
v0.1.57 win8
輸入藏文後，undo 的快捷鍵可還原到輸入藏文前的狀態，再用 redo 快捷鍵可使文章變成輸入藏文後的狀態
但 navigation bar 的 undo 和 redo 沒有作用

**Comment by kmsheng** [comment]
@chiehan1 已在 v0.1.62 修正

**Comment by chiehan1** [comment]
test ok in v0.1.62
