### ISSUE TITLE
使用 replace 後，navigation bar 的 undo 和 redo 不會還原文字到 replace 前的狀態

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#112]
v0.1.57 win8
使用replace後，可用快捷鍵的 undo 還原文字到 replace 前的狀態，也可再用 redo 快捷鍵重新讓文字變成 replace 後的狀態

但 navigation bar 的 undo 和 redo 則沒有作用

**Comment by kmsheng** [comment]
@chiehan1 已在 v0.1.62 修正

**Comment by chiehan1** [comment]
test ok in v0.1.62
thank you
