### ISSUE TITLE
Images go wrong after using save-as with the same doc name

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#114]
test in windows8 with v0.1.57 and v0.1.58
test file：
https://drive.google.com/open?id=0BwIL9c-GJgOZZkhuX2o2NkJ0Nzg
1. Import the test file. (use 'import zip')
2. Show the 'save as' window, don't change doc name and just click 'save as'.
3. Click 'cancel' and the 'save as' window will close.
4. Go to the other page, we will find that the images will become small icons.

![saveas1](https://cloud.githubusercontent.com/assets/13195099/13453020/f19446f2-e087-11e5-9b1f-3626095f408d.JPG)

![saveas2](https://cloud.githubusercontent.com/assets/13195099/13453024/f52e3f70-e087-11e5-9cc3-0252b2bd7097.JPG)

**Comment by kmsheng** [comment]
@chiehan1  已在 v0.1.62 修正

**Comment by chiehan1** [comment]
test ok in v0.1.62
