### ISSUE TITLE
Confirm when users close ketaka-lite with unsaved docs

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#115]
Before closing ketaka-lite with **unsaved docs**, an inquiring window will show up.

There are a description and three buttons in the inquiring window,
**Description**: 
There are (how many? 1 or 3 or ... ) docs unsaved.
Do you want to save the docs before closing Ketaka-lite? 
**Buttons**: Yes, No, Cancel

**Yes** button:  Show saving windows one by one for each unsaved docs, and close ketaka-lite after all the docs being saved.
**No** button: Close ketaka-lite anyway.
**Cancel** button: Don't close ketaka-lite, no further action happens, only close the inquiring window.

**Comment by kmsheng** [comment]
@chiehan1 已在 v0.1.62 修正

**Comment by chiehan1** [comment]
@kmsheng 請問可以加上 cancel button 嗎?
和關掉未存檔的 tab 一樣的 cancel button，按了會關掉跳出來的詢問視窗，其他什麼都不做

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.63

**Comment by chiehan1** [comment]
test ok in v0.1.64

**Comment by chiehan1** [comment]
v0.2.7
更改兩個以上的 tab，沒存檔就關掉 ketaka-lite
只會詢問 focus 的 tab 要不要 save and close
其他沒存檔的 tab 不會詢問，這些 tab 更改過的內容也不會被儲存

# 

補上問題的描述：

mac 和 windows 都有同樣問題
1. 開新 tab untitled
2. 開新 tag untitled1
3. 在 untitled 打字
4. 在 untitled1 打字
5. 關掉 ketaka-lite
6. 勾選 save and close
7. 重開 ketaka-lite 和這兩個 tab
8. untitled 空白, untitled1 有存到檔

如果是 focus 在第一個 tab 時，關 ketaka-lite，就會正常

**Comment by kmsheng** [comment]
fixed in 0.2.8

**Comment by chiehan1** [comment]
test ok in macOS 10.12.1 and windows7
