### ISSUE TITLE
reserve tags for "export file with pb" behavior

### ISSUE THREAD

**Issue by kmsheng** [karmapa/ketaka-lite#117]

**Comment by kmsheng** [comment]
@rickie120243 目前 0.1.66 已照法海師 skype 討論的內容實作, 請看看

**Comment by chiehan1** [comment]
test in v0.1.66 in windows7

感謝 @rickie120243 @kmsheng 

我記錄了目前 import 的行為

import 的 tag 已依照 tag element attribute 標上辨識度高的顏色

<tag1></tag1>如果中間沒有文字內容， import 會整合成 <tag1/>

遇到 <add> 這種有問題的 tag, 會自動在文字內容最後加上 </add> ，內容已不會消失，要請托資料組檢查原始 xml 資料修正這種 tag

export 後 tag 也都保留

以上都沒有問題

另外，import 的 xml 有兩個以上的 division 或 vol tag，需要跳出警示，不讓使用者 import，這一點我另外開個 issue 

感謝

**Comment by chiehan1** [comment]
已把後續的問題分成下列 issue，所以這個 issue 關掉
#118 
#119 
#120 
#121
