### ISSUE TITLE
Don't allow users to import xml or xmls with multiple division or vol tags

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#118]
匯入xml 的文件時，division tag 最多只能有一個， vol tag 也是最多只能有一個， 如果偵測到兩個以上的 division tag 或 vol tag ，要跳出警示，不允許使用者匯入
感謝!!

**Comment by kmsheng** [comment]
已在 v0.1.67 實作

**Comment by chiehan1** [comment]
test ok in v0.1.67 in windows8 and mac
