### ISSUE TITLE
Please reserve original line break character like this "<division/>line break<vol/>line break<pb id>" 

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#121]
目前 import 的文件如果是 
<division"/>
<vol/>
<pb id="1.1b"/>

export 以後
<division"/>
<vol/><pb id="1.1b"/>

希望能保留原本的 line break

感謝!!

**Comment by kmsheng** [comment]
已在 v0.1.67 實作

**Comment by chiehan1** [comment]
test ok in v0.1.67 in windows8 and mac
