### ISSUE TITLE
The cursor will move to the next position after pressing "control + f" or "control + shift + f"

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#123]
其實不太知道要歸在 bug 還是 enhancement
v0.1.66
windows 測試沒有這個問題
在 mac 中，游標在第二行的 1 前面
![1](https://cloud.githubusercontent.com/assets/13195099/13631414/806cfab2-e61f-11e5-8f4c-6501f6592401.png)
按預設的快捷鍵叫出搜尋或取代 (按快捷鍵才會，用 edit 下拉式選單裡的 find 和 replace 不會這樣)
再關掉搜尋和取代，會發現 cursor 往後移一個位置，移到第二行的 1 後面

怕會造成 mac 搜尋和取代的時候 double highlight 會多往後跳一個的問題，使用者想要看到 highlight 目前 cursor 後面的字被 double highlight，可是會變成跳到再下一個字，如果這個字在比較後面，會從當前文章跳到後面的文章，擔心對使用者有視覺上的不便

**Comment by kmsheng** [comment]
跟 codemirror 內建的熱鍵衝到了

https://codemirror.net/doc/manual.html
goCharRightRight, Ctrl-F (Mac)
Move the cursor one character right, going to the next line when hitting the end of line.

**Comment by kmsheng** [comment]
例如 ctrl + k 可以刪掉後面一整行
ctrl + d 可以幹掉一個字元

**Comment by chiehan1** [comment]
test ok in v0.1.67 in mac
