### ISSUE TITLE
Hope to add edit docs option in app menu to delete project

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#125]
希望在 ~~toobar 最右邊~~ app 下拉式選單新增選項 ，點選會開啟 docs 資料夾
Mac: ~/Library/Application Support/ketaka-lite/docs 
Windows: %appdata%
讓使用者方便管理 docs 資料夾裡的專案

**Comment by kmsheng** [comment]
@chiehan1  可以放在功能選單的 App > Settings 裡面嗎 ?
toolbar 現在已經太多按鈕了, 在窄解析度的情況下很可能會跑版

**Comment by chiehan1** [comment]
法海師想加在 doc setting 的視窗裡(左圖)
如果不能加在 doc setting 視窗裡的話
希望能加在 app 的下拉式選單(右圖)，法海師認為加在 app 選單的 settings 裡太不方便了 
![gotodoc3](https://cloud.githubusercontent.com/assets/13195099/13771709/c0efed1a-eaca-11e5-899c-1a31b9597ef6.JPG)

**Comment by kmsheng** [comment]
@chiehan1 兩張圖的做法都可以做, 但是我比較建議右圖

**Comment by chiehan1** [comment]
感謝建議，剛剛詢問過法海師，那麼就改成採用右圖直接在 app 的下拉式選單裡新增一個選項開啟 docs 資料夾，感謝

**Comment by kmsheng** [comment]
@chiehan1 https://github.com/karmapa/ketaka-lite/issues/126 的問題解決的話, 這張應該就不用做了吧 ?

**Comment by chiehan1** [comment]
詢問過 @lamalien 
因為當初開會的確沒有決定刪除機制，但是後來發現 import 進去的專案會越積越多
@lamalien 認為如果現在加上刪除機制會讓整體架構變得很亂的話
或許也可以改 doc 路徑，讓 doc 不要在隱藏的資料夾內，也不要藏那麼深
以 windows 來說，可以放在 C 槽下面，讓使用者可以很快找到 doc 資料夾
這樣這個 doc 資料夾可能還要改個特殊的名字，才不會和既有的資料夾名字重複衝突

**Comment by kmsheng** [comment]
@chiehan1 我建議直接把刪除做在程式裡面, ( 就是開啟 doc 的視窗, 很早以前 demo 過 ) 如果怕誤刪可以多加一個確認詢問 ?
因為不是所有使用者都會剛好 mount 在 C:/, 如果開放使用者指定 docs 的位置延伸問題也滿多的

**Comment by chiehan1** [comment]
@lamalien 已確認
新增 edit docs 選項在app menu 的 open 下方
點選後跳出 check-box
每個既有的 bamboo 旁邊有小框框
使用者可勾選小框框，看要刪除哪幾個 bamboos
勾選完按 delete 按鈕，跳出 confirm 視窗
使用者確認後，刪除這些勾選的 bamboos
check-box 自動關閉

使用者也可按 cancel 按鈕，隨時關掉 check-box，不執行刪除動作

![edit docs](https://cloud.githubusercontent.com/assets/13195099/14137217/7479cb2e-f699-11e5-9edd-5e7578141f85.png)

辛苦了，感謝

**Comment by kmsheng** [comment]
fixed in v0.1.73

**Comment by chiehan1** [comment]
test ok in v0.1.74 in mac and windows8
thank you
