### ISSUE TITLE
Cannot import big zip in windows

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#126]
test v0.1.67

big zip, over 300 Mb
https://drive.google.com/open?id=0BwIL9c-GJgOZTklkaTNoWGlDQTQ

small zip, about 100 Mb
https://drive.google.com/open?id=0BwIL9c-GJgOZVFRadkV3dWUybnc

In Mac, it's ok to import both zip file, although importing time is a little longer for big zip.

In Windows8, it's ok to import small zip, but ketaka-lite will crash when importing big zip. But it's interesting that if users unzip the big zip file and put those unzip files into the docs folder in %appdata%, users can open the project through the 'open' option in navigation bar of ketaka-lite.

**Comment by kmsheng** [comment]
@chiehan1 換掉會吃很多記憶體的 unzip library 了, 請試試 v0.1.68

**Comment by chiehan1** [comment]
fixed in v0.1.69
already tested a 332Mb zip file for successful importing in windows8 and a 361Mb zip file in mac
thank you
