### ISSUE TITLE
Hope to keep texts between no attribute tags:  " <someId > text </someId> "

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#127]
In v0.1.67,
If the imported tags are with attributes: (Using ttitle tag as example here.)
<ttitle n="1"> text of ttitle </ttitle>
the output will be the same:
<ttitle n="1"> text of ttitle </ttitle>

However, if imported tags are with no attribute:
<ttitle> text of ttitle </ttitle>
the text will disappear after importing and in output:
<ttitle ></ttitle>

@lamalien hopes the output will still be:
<ttitle > text of ttitle </ttitle>

Please also reserve the text between the no attribute tags. Thank you!!

And here is the link of test data.
https://drive.google.com/open?id=0BwIL9c-GJgOZUUtYUmtVRVZDZFE

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.69

**Comment by chiehan1** [comment]
test ok in mac and windows8 in V0.1.69
thank you!!
