### ISSUE TITLE
If the closing tag is missing, stop importing and tell users that the tag is in which page and which file

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#128]
Like this 
<pb id="2.3a"/>
<tittle> some text

Stop importing and show warning that the tag format is wrong in 2.3a.

**Comment by kmsheng** [comment]
@chiehan1 可以幫我問一下法海師, 如果是自動補完可以嗎?
例如 <pb id="2.3a"/>
<tittle> some text <pb id="1.1b"/>

會自動補成

<tittle> some text </title><pb id="1.1b"/>

**Comment by chiehan1** [comment]
以 ttitle 為例，通常文章是這樣
<pb id=""/>
textA<ttitle>textB</ttitle>textC
<pb id=""/>

如果 ttitle 的 closing tag 缺失，自動補上
會變成
<pb id=""/>
textA<ttitle>textB textC </ttitle>
<pb id=""/>
變成 tag 對，可是位置錯，以後檢查更難
所以恐怕不太行

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.73

**Comment by chiehan1** [comment]
Please add warning message that the tag is in which page and in which file.
Thank you!

which page means if there is the text below, it will warn that the "add" tag is in pb id "9.1b"
<pb id="9.1a"/>
1
<pb id="9.1b"/>
<add>
<pb id="9.2a"/>
3
<pb id="9.2b"/>
4
<pb id="9.3a"/>
5
<pb id="9.3b"/>
6

**Comment by kmsheng** [comment]
@chiehan1  fixed in v0.1.75

**Comment by chiehan1** [comment]
Test ok in mac and windows8 in v0.1.75
thank you
