### ISSUE TITLE
The Import Status window will hang up on the screen after the warning message showing.

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#129]
In v0.1.69 in mac and windows8

During importing, if the red warning message shows and stop importing, the Import Status window will hang up on the screen.

My test file is with duplicated pb id:
<pb id="1.1d"/>
<pb id="1.1d"/>

![2016-03-31 4 16 53](https://cloud.githubusercontent.com/assets/13195099/14169719/132f4772-f75c-11e5-8d47-1ab20fa3ae26.png)

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.73

**Comment by chiehan1** [comment]
Test ok in v0.1.74 in mac and windows
Thank you!!
