### ISSUE TITLE
Icons of tool bar disappear

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#130]
Both in mac and windows version in V0.1.74
![slice 1](https://cloud.githubusercontent.com/assets/13195099/14196053/061e6eae-f7f3-11e5-913d-9d49334d5e3d.png)

**Comment by kmsheng** [comment]
@chiehan1 how to reproduce this ?

**Comment by chiehan1** [comment]
I just open a tab in ketaka-lite v0.1.74.
Or could you rebuild v0.1.74?

**Comment by kmsheng** [comment]
@chiehan1 please try v0.1.75

**Comment by chiehan1** [comment]
in Mac and windows8,
the icons still disappear.  
@rickie120243 tried v0.1.75 in mac, and the icons also disappear.

**Comment by kmsheng** [comment]
@chiehan1 found the problem, please try @v0.1.76

**Comment by chiehan1** [comment]
@kmsheng Thank you! The problem is fixed in v0.1.76 in Mac and Windows8
