### ISSUE TITLE
Cannot save project by hotkey and from app menu in mac version

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#131]
When users click hotkey "control + s", or select "save" from app menu，
the bamboo is still not saved.
The  star * is still there.
And when users close the tab, the checking window will show up to ask whether to save it or not.
It means the bamboo only can be saved when closing.
This issue is only in mac version, the windows version is normal.  
![slice 1](https://cloud.githubusercontent.com/assets/13195099/14196238/fd87cfb8-f7f4-11e5-847e-e72b49af37aa.png)

**Comment by kmsheng** [comment]
this only happens when an opened doc is deleted, i don't think it related to os

**Comment by chiehan1** [comment]
yes, thank you!
I'll close it.
