### ISSUE TITLE
匯入專案後，使用者只進行切換頁的動作後，點選 undo，會 undo 回所有切換頁面的內容 (請見影片)

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#134]
Should ketaka-lite block this kind of undo.

https://www.youtube.com/watch?v=5v-B46FoPcI

**Comment by chiehan1** [comment]
同樣的問題也會出現在文字編輯中，影片中有 1 2 3 頁
從第 3 頁開始新增內容，最後在第一頁連續按 undo，會出現 2 3 頁的內容

https://www.youtube.com/watch?v=OnxWFJr72PM

**Comment by kmsheng** [comment]
這個很久以前就討論過了, 那時因為要重寫 history system 會花較多時間所以就沒處理了。

**Comment by kmsheng** [comment]
@chiehan1  已在 v0.1.84 重做整個 history system

**Comment by chiehan1** [comment]
test ok in v0.1.86 in windows8 and mac, thank you
