### ISSUE TITLE
搜尋或取代，輸入新的關鍵字，畫面才自動往下跳到符合的字 (影片)

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#135]
v0.1.75

目前的搜尋或取代，重新開啟搜尋欄，如果搜尋欄有之前留下的舊關鍵字時，畫面會自動往下跳到下一個符合的字

是否限定成輸入新的關鍵字時，畫面才自動往下跳到下一個符合的字

而如果搜尋欄再次開啟，留有舊的關鍵字，此時雖然算出舊關鍵字的符合數和 highlight 符合的字
但是除非使用者去按搜尋下一個或上一個字，否則畫面不移動

KETAKA-Lite 目前的實作，影片下方有說明
https://www.youtube.com/watch?v=ZAB5lqQRVW0&feature=youtu.be

sublime 的例子，影片下方有說明
https://www.youtube.com/watch?v=1AO5OYyfcSM&feature=youtu.be

**Comment by kmsheng** [comment]
@chiehan1 我測試目前版本似乎沒這問題耶?
