### ISSUE TITLE
從游標位置為起點，搜尋下一個字或上一個字 (影片)

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#136]
v0.1.75
目前 KETAKA-Lite 就算游標位置已變動，搜尋上一個字或下一個字時
會跳回一開始搜尋的位置再往下依序搜尋
請見影片，影片後段錄了 sublime 當對照
https://youtu.be/0CHfV39IRLs

以下整理目前 find 的行為，整體比較清楚
目前新增的有
(1)開啟搜尋，focus 不會跳回第一行 #91 
  1.開啟搜尋，搜尋欄是空的，從目前游標位置為起點，雙重 highlight 下一個字
  2.開啟搜尋，搜尋欄留有舊的關鍵字，從目前游標位置為起點，雙重 highlight 下一個字
  3.開啟搜尋，更換關鍵字，從目前游標位置為起點，雙重 highlight 下一個字
https://youtu.be/HpCciJlJgs8
(2)highlight 所有符合的字
(3)從目前游標位置為起點，往後算出符合的數目
(4)可以跨頁跳下一個和跳上一個符合的字
(5)搜尋欄開啟的狀態，會記錄查過的字的搜尋起始位置
https://youtu.be/J9uOOJhw1M4

**Comment by kmsheng** [comment]
@chiehan1  fixed in 0.1.81

**Comment by chiehan1** [comment]
test ok in v0.1.83 in mac and windows8, thank you
