### ISSUE TITLE
無法同時開啟 save as 儲存的新專案 和 save as 之前的專案 (影片)

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#137]
v0.1.75
請見影片
https://youtu.be/ucOc55TcSwQ
影片中先建立的名為 save 的專案
再用 save as 儲存了名為 saveas 的專案
再另外建立一個叫 other 的專案
可以看到無法同時開啟 save 和 saveas 兩個專案

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.78

**Comment by chiehan1** [comment]
Test ok in v0.1.79 in mac and windows8, thank you!
