### ISSUE TITLE
希望在 navigation bar 的 About KETAKA-Lite  寫上 版本號 (mac)

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#139]
希望在 navigation bar 的 About KETAKA-Lite  寫上版本號，感謝
![version](https://cloud.githubusercontent.com/assets/13195099/14312596/7ebd00f2-fc1f-11e5-8b51-6bf16529b2ee.png)

**Comment by kmsheng** [comment]
fixed in v0.1.77, the first one is electron version and the other in parentheses is app version.

**Comment by chiehan1** [comment]
Test ok in mac in v0.1.79. Thank you!
