### ISSUE TITLE
希望在 navigation bar 的 Help menu 加上 About KETAKA-Lite 選項 (windows 版)

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#140]
和 #139 是相關的，目的是讓使用者知道版本
windows 版不像 mac，navigation bar 預設有 About KETAKA-Lite 的選項
在看了 windows 的一些編輯器以後，發現這些編輯器的版本號是放在 Help menu 中
所以希望能在 windows 版的 KETAKA-Lite 的 Help menu 新增 About KETAKA-Lite 的選項，感謝

![version2](https://cloud.githubusercontent.com/assets/13195099/14339070/48772d3a-fcae-11e5-982d-805e810f8ca3.png)

按下去以後會跳出小視窗
希望小視窗的內容先和 mac 版一樣有 logo 和版本號，感謝
(小視窗的樣式不一定要照這個圖)

![version1](https://cloud.githubusercontent.com/assets/13195099/14339072/4e8de984-fcae-11e5-93be-b611aeb48f24.png)

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.86

**Comment by chiehan1** [comment]
在兩台 windows8 和 一台windows10 測試 v0.1.86
點選 Help menu 中的 About KETAKA-Lite
沒有視窗跳出

**Comment by kmsheng** [comment]
electron 的 role about 只支援 mac, windows 要做的話要用 HTML, 不會完全一樣

**Comment by kmsheng** [comment]
@chiehan1 added in v0.1.87

**Comment by chiehan1** [comment]
在 windows7 測試 v0.1.89
已有視窗跳出，視窗內容雖然沒有 logo，但重點是已有版本號，感謝!
