### ISSUE TITLE
兩個 project 都已存檔，直接關掉其他 project，目前 focus 的 project 的文字部分會消失

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#141]
v0.1.79

請見影片
同時開啟兩個存檔的專案，一個是 project 1，一個是 project 2
先 focus 在 project 2
如果關掉 focus 的專案，不會有問題發生
但如果直接關掉沒有 focus 的 project 1
project 2 的文字部分會消失
https://www.youtube.com/watch?v=MnFlGBPwkX0

**Comment by chiehan1** [comment]
補充
回去試了 v0.1.76 版，也有這個情形

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.83

**Comment by chiehan1** [comment]
Test ok in v0.1.83, thank you
