### ISSUE TITLE
focus 未儲存的專案， 想關掉其他已儲存的專案， 但卻跳出詢問 focus 的專案是否存檔的視窗

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#142]
v0.1.79
請見影片

focus 未儲存的專案，
想直接關掉其他已儲存的專案，
但卻跳出詢問目前 focus 的專案是否存檔的視窗

https://www.youtube.com/watch?v=nZNweggnVsU

**Comment by kmsheng** [comment]
@chiehan1 fixed in 0.1.81

**Comment by chiehan1** [comment]
test ok in v0.1.83 in mac and windows8, thank you
