### ISSUE TITLE
doc name 如果有 dash 符號，export zip 之後，再 import 這個 zip，會出現錯誤

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#143]
請見影片

doc name 如果有 dash 符號 -
export zip 之後
再 import 這個 zip
會出現錯誤
且 import status 視窗無法關閉
需重開 KETAKA-Lite

https://www.youtube.com/watch?v=A6oQz7GTZCo&feature=youtu.be

**Comment by kmsheng** [comment]
@chiehan1 fixed in 0.1.86

**Comment by chiehan1** [comment]
Test ok in v0.1.86, thank you!
