### ISSUE TITLE
undo redo 快捷鍵沒反應

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#144]
v0.1.86
按了 undo 和 redo 的快捷鍵沒反應

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.87

**Comment by chiehan1** [comment]
分別在 windows7 和 mac 測試 v0.1.89
windows7 使用 ctrl + z 或 mac 使用 command + z
目前也都沒辦法 redo

**Comment by kmsheng** [comment]
@chiehan1 在 settings 頁面多加了 undo 與 redo 的快捷鍵設定, 目前預設是 ctrl + z ( undo )與 ctrl + shift + z ( redo ), 請試試 v0.1.90

**Comment by chiehan1** [comment]
test ok in v0.1.90 in mac and windows
thank you!!
