### ISSUE TITLE
upload image 同系列的頁碼的圖，記錄連動

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#145]
測試檔下載 
https://drive.google.com/open?id=0B7IngcS_Eo5JTi14OWJlUHNBTUk

(1)
1.1a 1.2a 1.3a upload image 的圖只能存成同一張
1.1b 1.2b 1.3b 是同一張
2.1a 2.2a 2.3a 是同一張
2.1b 2.2b 2.3b 是同一張
以上無法存成每一頁不同張圖
https://www.youtube.com/watch?v=ST2zddYck8k

(2)同樣的情形
1.1a 1.2a 同一張 1.1b 1.2b 同一張 1.1c 1.2c 同一張 1.1d 1.2d 同一張
https://www.youtube.com/watch?v=qAUO3V0LqMI

(3)這種頁碼也是一樣
1.1 1.2 1.3 同一張 2.1 2.2 2.3 同一張
https://www.youtube.com/watch?v=1kCG3exfjYQ

(4)
必需是不同系列的頁碼，才可以 upload 不同張圖
https://www.youtube.com/watch?v=i6nR2HxYws0

(5)
KETAKA-Lite 不關掉重開的情況下
一個頁碼一旦 upload 過某張圖
之後這個頁碼就不能 upload 別張圖
https://www.youtube.com/watch?v=Tbp9ir8JwnY
https://www.youtube.com/watch?v=A_9AInhghM8

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.87

**Comment by chiehan1** [comment]
在 windows7 和 mac 測試 v0.1.89
1.1a 1.2a 1.3a;
1.1 1.2 1.3;
這種同系列的頁碼，都可以 upload 相同的圖了
感謝!

(5) 的問題和這個 issue 標題不符，另外開一個 issue
