### ISSUE TITLE
windows8， window + space，再按 k，會關掉 tab

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#146]
v0.1.86
先按 window + space (切換輸入法)
再按 k 鍵，會關掉 tab

**Comment by kmsheng** [comment]
@chiehan1 window + space 有確實 release 嗎?

**Comment by chiehan1** [comment]
v0.1.86 和 v0.1.89 在 windows7 都沒有這個問題
現在手邊沒有 windows8，星期一會用 windows8 試試看

**Comment by chiehan1** [comment]
v0.1.89
只有 windows8 有這個問題
windows7 和 windows10 切換語系的快捷鍵不是 windows + space，沒有這個問題

影片約 5 秒的時候，按 windows + space 切換語系
12 秒的時候在 KETAKA-Lite 文字區打字，打 k
tab 關閉
https://youtu.be/K1X8vfl7za0

**Comment by chiehan1** [comment]
按 windows + space
再按了 j 會觸發新增 tab

**Comment by kmsheng** [comment]
@chiehan1 那可以請你測一下把快捷鍵改掉不要用 cmd 可以嗎 ?

**Comment by chiehan1** [comment]
測了 v0.1.94 windows8
改了 ketaka-lite 的 close tab 和 add tab hotkey 的 cmd
就沒有這個情形了

**Comment by chiehan1** [comment]
目前會在使用手冊上註記，請 win8 的使用者去 setting 改快捷鍵

**Comment by kmsheng** [comment]
@chiehan1 我可以做到 偵測如果是 windows, 預設就用 ctrl 快捷鍵
但是使用者仍然還是可以自己設定成 cmd ? 因為 windows8 內建有

我建議這部分還是要寫在手冊上, 因為硬是要擋掉他設定的某個鍵也是很奇怪

**Comment by kmsheng** [comment]
@chiehan1 v0.1.97 預設已改成會用 os 判斷

**Comment by chiehan1** [comment]
感謝！
windows 8 測試了 v0.1.97-1
如果使用者之前的版本的 hotkeys 是 cmd + k, cmd + j
打開 v0.1.97-1 的 hotkeys 一樣會是 cmd + k, cmd + j
要先在 settings 裡按 reset shorcuts to default 
hotkeys 才會變成 ctrl + k, ctrl + j

**Comment by kmsheng** [comment]
先這樣吧, 如果改成一升版本就 reset settings 這樣對使用者來說也不便

**Comment by chiehan1** [comment]
了解，感謝!!
