### ISSUE TITLE
focus 已儲存的 tab，直接關閉其他未儲存的 tab，請問是否先 focus 到這個未儲存的 tab 再跳出詢問視窗

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#147]
KETAKA-Lite v0.1.86
開啟兩個 tab
focus 已儲存的 tab
直接關閉未儲存的 tab
雖然跳出詢問存檔的視窗，但結果關閉的會是目前 focus 的 tab
請問這種情形是否像 sublime 的行為較好，會先 focus 點選關閉的 tab，再跳出詢問存檔的視窗？
感謝！

影片連結如下
https://youtu.be/KqSp37q8-RM

**Comment by chiehan1** [comment]
補上如果兩個 tab 都未儲存的影片
https://youtu.be/3EPRDfCJZTM
和上面的狀況類似
focus 未儲存的第一個 tab，直接關掉未儲存的第二個 tab
雖然跳出詢問視窗，可是關掉的卻是第一個 tab

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.87

**Comment by chiehan1** [comment]
在 mac 和 windows7 測試 v0.1.89
以新增此功能，感謝
