### ISSUE TITLE
import 的 zip 檔，和 docs 中的專案同名時，希望先有警示告知 docs 的哪個檔案會被覆蓋，並詢問使用者是否 import

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#148]
import 的 zip 檔，和 docs 中的專案同名時
希望先有警示告知 docs 的哪個檔案會被覆蓋
並詢問使用者是否 import
感謝

**Comment by kmsheng** [comment]
@chiehan1 added in v0.1.87

**Comment by chiehan1** [comment]
在 mac 和 windows7 測試 v0.1.89，都 ok
感謝
