### ISSUE TITLE
KETAKA-Lite 程式不關掉重開，一個頁碼一旦 upload 過某張圖，不存檔，關掉 tab 再 open，這個頁碼不能 upload 別張圖

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#149]
v0.1.89
KETAKA-Lite 程式不關掉重開的情況下
一個頁碼一旦 upload 過某張圖
之後這個頁碼就不能 upload 別張圖

影片中的頁碼 1，upload 了 1 的圖；頁碼 1a，upload 了 1a 的圖
不存檔，關掉 tab，重新 open
頁碼 1 upload 的圖是 ad，但卻變成 upload 了 1 的圖
頁碼 1a upload 的圖是 ac，但卻 upload 了 1a 的圖 
https://www.youtube.com/watch?v=A_9AInhghM8

**Comment by kmsheng** [comment]
@chiehan1 已在 v0.1.90 修正

**Comment by chiehan1** [comment]
test v0.1.90 ok in mac and windows8
thank you!
