### ISSUE TITLE
文字編輯區，pagebreak 以後，點選 undo 的機制

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#150]
使用者有時會 pagebreak 分頁分錯
自己剪下文字貼回前一頁，有時也會剪錯貼錯，希望能有較方便的 undo 機制

向法海師請教了兩種 undo 的機制

以下假設匯入之後的 tab 有三頁，page1 page2 page3

第一種
匯入圖和文字檔以後 (或是匯入 zip 檔)
時間點 1 是匯入後的初始狀態，這時任何頁碼點選 undo 都不應有反應
時間點 1 2 3 是現在的 pagebreak 機制，pagebreak 後會自動 focus 下一頁(畫面自動跳下一頁，圖的紅色框框表示目前 focus 的頁碼)
時間點 4，就是 focus 時間點 3 的第 3 頁時，使用 undo，等於回到時間點 2 的狀態
時間點 5，就是 focus 時間點 4 的第 2 頁時，使用 undo，等於回到時間點 1
這時任何頁碼點選 undo 也不會有反應了
(在時間點 2 的第 2 頁使用 undo，也會回到時間點 1)

![pagebreakundo1](https://cloud.githubusercontent.com/assets/13195099/14407708/64d01b0e-ff06-11e5-80c4-0c9e38548f40.jpg)

但是後來想到了如果使用者邊在每一頁做文字編輯邊 pagebreak，然後才想要 undo pagebreak，
是否會變得很複雜，
例如使用者如果在第 2 頁做了文字編輯，再去第三頁點 undo，那麼會先 undo pagebreak 還是 undo 第 2 頁的文字編輯

以上

接下來是第二種機制

每一頁的 memory 都是獨立的
每一頁都可以獨自 undo 到剛匯入時的狀態

![pagebreakundo2](https://cloud.githubusercontent.com/assets/13195099/14407917/2237c400-ff0f-11e5-87fc-9c36722a8572.png)

第二種機制，在 pagebreak 後，先去 undo 第一頁，再去 undo 第二頁，再去 undo 第三頁
但如果不照圖的順序先 undo 第二頁，再去 undo 第一頁，再去 undo 第三頁
或其他順序，結果都可以各自 undo 回剛匯入的狀態

每一頁如果各自 undo 回到匯入時的初始狀態，那一頁再按 undo 就不會有反應
例如時間點 1 剛匯入時，到每一頁按 undo，都不會有反應
第 1 頁 (page1) 在時間點 5 已經回到匯入時的狀態，再按 undo 不會有反應
第 2 頁 (page2) 在時間點 8 已經回到匯入時的狀態，再按 undo 也不會有反應
第 3 頁 (page3) 在時間點 10 按 undo 不會有反應

以上

不知哪種機制比較可行，
或是兩種都不行，都可以再討論，感謝!!

**Comment by kmsheng** [comment]
兩種做法對使用者來說都不好, 而且也不易實作
1. undo & redo 不應該牽扯到換頁, 要處理的例外太多, 而且對使用者的認知上也太過複雜
2. 不好的原因是因為需要使用者主動去換頁

如果是我的話會比較傾向做一個 undo 最後一次 pagebreak 的按鈕, 這個不牽扯到任何 history
按下去就是把那兩頁內容強制設定回 pagebreak 之前, 然後頁面也切回去

**Comment by chiehan1** [comment]
這樣的結果比較類似 1 的做法，只是獨立出來單獨變成一個特殊的 undo pagebreak按鈕
另外還要請您再加一個 redo pagebreak 按鈕

**Comment by chiehan1** [comment]
這似乎又是另一個有問題的地方
直接文字編輯後，page break
回前頁按 undo，回復的順序有些奇怪
https://youtu.be/uokuxSeiTxg

**Comment by chiehan1** [comment]
@kmsheng  您好
您的建議已經跟 @lamalien 說過
@lamalien 也同意另外做 undo pagebreak 的功能

有些地方似乎有點複雜

如某一頁文字編輯完以後再 pagebreak
undo pagebreak 以後
再按普通的 undo
會不會還能 undo 文字編輯的部分

**Comment by kmsheng** [comment]
@chiehan1 
我的想法是 pagebreak 與 undo pagebreak 的紀錄都不應該加入 undo / redo button 的 history

**Comment by chiehan1** [comment]
是的

只是 pagebreak 的動作和 undo / redo button 的 history 似乎感覺上還是會有牽扯

現在 import 進來不做任何文字編輯，只做 pagebreak
每一頁按 undo / redo 都沒有作用
表示紀錄都不會進到 undo / redo button 的 history

只是做了文字編輯之後
比如說 a 頁的內容從頭到尾做了許多文字編輯
使用者從 a 頁中間 pagebreak
undo / redo history 已經紀錄的一些文字段落被 pagebreak 到下一頁 
(被 pagebreak 到下一頁的文字段落簡稱 pagebreak text)
使用者回到 a 頁，
再按 undo / redo
undo / redo history 紀錄 pagebreak text 的部分
就會被 undo / redo 出來，目前用起來，使用者反應有 undo / redo 會亂跳的感覺
大部分用的人會覺得 pagebreak 有進到的 undo / redo 的 history 裡

或是說 pagebreak 完以後，pagebreak 相關的那兩頁的 undo / redo history 都重置，似乎也不是好方法

另外還想了一些疑問

如果有了 undo pagebreak，如果使用者 pagebreak 到了中間的頁碼，後半段的文章都從外面貼進來編輯，又不小心按了 undo pagebreak，結果中間的兩頁變回編輯前的狀態，好像也需要考量這種情況

又，假設 pagebrak 前，前後兩頁是狀態一
剛 pagebreak 完，前後兩頁是狀態二
接著在這兩頁做文字編輯做完，是狀態三
這時 undo pagebreak 回到狀態一
那麼照理說 redo pagebreak 應該要回到狀態二 還是 狀態三呢?

**Comment by kmsheng** [comment]
history 應該只記錄到 pagebreak 按下之前, 現在版本會紀錄是錯誤的, 之後會修掉。
反正所有分頁動作都不進 history 就對了

我就是不希望這個軟體變成 undo / redo 會觸發換頁動作

**Comment by chiehan1** [comment]
經過 2016/4/14 開會，決定
做一個 undo 最後一次 pagebreak 的按鈕, 不牽扯到單獨頁面的 history
按下去會把 undo 相關兩頁的內容強制設定回 pagebreak 之前, 頁面也切回去
感謝！

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.101

**Comment by chiehan1** [comment]
問題發新的 issue #163
