### ISSUE TITLE
undo 和 redo 會自動縮減後方文字行數 和 自動分行

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#152]
undo 和 redo 會影響後面文字內容
像是縮減行數
後面文字自動分行

請見影片
https://www.youtube.com/watch?v=Kpiwzr8bs9E
對照 sunlime
https://youtu.be/r_hKTDEpNQs

**Comment by kmsheng** [comment]
@chiehan1 已在 v1.0.94 修正這個問題

**Comment by chiehan1** [comment]
測試了 mac 和 windows
v0.1.94 已修正
感謝
