### ISSUE TITLE
希望 undo 和 redo 時，cursor 能停留在進行 undo 和 redo 以後，文字段落更改的地方，不要跳回第一行

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#153]
如果 undo 和 redo 完會自動跳回第一行，文字畫面會瞬移，cursor 也沒有 focus 在原本的段落和畫面，
使用者可能較為不便

影片後段錄了 sunlime 對照，感謝
https://youtu.be/omxG5ZuniwY

**Comment by kmsheng** [comment]
@chiehan1 已在 v1.0.94 修正這個問題

**Comment by chiehan1** [comment]
在 mac 和 windows8 測試
v0.1.94 已修正
感謝!!
