### ISSUE TITLE
除了 system imput，其他三種輸入法都無法覆寫選取的文字

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#154]
除了 system imput，其他三種輸入法都無法覆寫選取的文字

https://youtu.be/K7JEC-gPirU

**Comment by kmsheng** [comment]
我剛切回之前的 commit 測試, 這問題之前就有了

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.97

**Comment by chiehan1** [comment]
test ok in v0.1.97-1 in mac and windows8
thank you!
