### ISSUE TITLE
匯出 zip 檔再匯入，匯入的 doc 和原來的 doc 無法同時開啟

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#155]
影片中先建立 doc1
匯出 zip 檔
將 doc1 改名為 doc2
匯入 doc1.zip

doc1 和 doc2 無法同時開啟，有錯誤訊息
請見影片，感謝
https://youtu.be/WzjoUbm5bhk

**Comment by kmsheng** [comment]
fixed in v0.1.96

**Comment by chiehan1** [comment]
test ok in v0.1.96 in mac and windows8
thank you!
