### ISSUE TITLE
希望 export zip 檔完成前禁止關閉 KETAKA-Lite

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#156]
因為 export zip 檔完成前，關閉 KETAKA-Lite
會產生毀損的 zip 檔
再次 import 此 zip 檔時
除了無法 import，KETAKA-Lite 也會定格在 import status 視窗，需整個關掉再開

所以希望如果使用者在 export zip 完成前關閉 KETAKA-Lite
能禁止使用者關閉並跳出警示告知使用者，請等 zip export 完成後再關程式
感謝!!

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.99

**Comment by chiehan1** [comment]
test ok in v0.1.99 in mac and windows8
thank you!!
