### ISSUE TITLE
希望當 doc 在未存檔狀態時 ( tab 有 * )，使用者 export zip，會自動幫使用者存檔，再 export zip

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#157]
希望當 doc 在未存檔狀態時 ( tab 有 \* )
使用者 export zip
會先跳出視窗告知使用者這個 doc 尚未存檔，未存檔的部分不會被 export，是否要繼續 export zip
感謝!!

**Comment by kmsheng** [comment]
@chiehan1 既然決定要匯出了, 我覺得應該是要幫他自動存擋再匯, 而不是多此一問

**Comment by chiehan1** [comment]
了解，issue 改成
希望當 doc 在未存檔狀態時 ( tab 有 \* )，使用者 export zip，會自動幫使用者存檔，再 export zip
感謝

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.99

**Comment by chiehan1** [comment]
test ok in v0.1.99 in mac and windows
thank you!
