### ISSUE TITLE
希望當 doc 在未存檔狀態時 ( tab 有 * )，使用者 export file with pb，會先自動存檔，再匯出

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#158]
和 #157 的情況相同
希望當 doc 在未存檔狀態時 ( tab 有 \* )
使用者 export file with pb
會先跳出視窗告知使用者這個 doc 尚未存檔，未存檔的部分不會被 export，是否要繼續 export file with pb
感謝!!

**Comment by kmsheng** [comment]
同 #157, 我覺得直接存擋就好 不需要多問

**Comment by chiehan1** [comment]
了解
希望當 doc 在未存檔狀態時 ( tab 有 \* )，使用者 export file with pb，會先自動存檔，再匯出
感謝

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.99

**Comment by chiehan1** [comment]
test ok in v0.1.99 in mac and windows8
thank you!
