### ISSUE TITLE
套用志軒新的 spellcheck 正字檢查

### ISSUE THREAD

**Issue by kmsheng** [karmapa/ketaka-lite#159]

**Comment by kmsheng** [comment]
@chiehan1 請捷安幫忙看一下 v0.1.99 套用上的新 spellcheck 有無問題

**Comment by chiehan1** [comment]
感謝!
請 @lamalien 試用

**Comment by chiehan1** [comment]
@lamalien 法海師試用 ok
不足的字，以後再慢慢加到字庫中
感謝 @kmsheng  @rickie120243

**Comment by chiehan1** [comment]
應該是 @kmsheng 關
