### ISSUE TITLE
當 cursor 移到圖片區時，圖片區右上角出現刪除圖片的 icon，可以單獨刪除圖片

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#160]
當 cursor 移到圖片區時，圖片區右上角出現刪除圖片的 icon，可以單獨刪除圖片

![group](https://cloud.githubusercontent.com/assets/13195099/14522786/d0b7ee5a-0262-11e6-8b39-a615f3e110ee.png)

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.100

**Comment by chiehan1** [comment]
~~但 upload image 以後會變成重疊畫面~~
沒有重疊畫面的問題

**Comment by chiehan1** [comment]
v0.1.100 mac windows8 test ok
