### ISSUE TITLE
希望被 pagebreak 的文字段落的 history，從原本的 history 被剔除掉

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#161]
請見影片
https://www.youtube.com/watch?v=uokuxSeiTxg&feature=youtu.be

**Comment by kmsheng** [comment]
@chiehan1 hello, 我測過目前應該沒有此問題

**Comment by chiehan1** [comment]
可能暫時不用修這個，不然 undo pagebreak 以後，回來的文字段落會沒有 history
這張票先關掉
