### ISSUE TITLE
頁碼符合頁碼規則時，upload 的 image 在 doc 資料夾中的圖檔名前面，不要加上 doc name

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#162]
頁碼符合頁碼規則時，upload 的 image 在 doc 資料夾中的圖檔名前面，不要加上 doc name

**Comment by kmsheng** [comment]
@chiehan1 已在 v0.1.100 修正此問題, 現在不是正規的 pb id 上傳圖片也不會被更改檔名了

**Comment by chiehan1** [comment]
目前試用都 ok
只是頁碼是 1a.1a 時，doc 裡的圖檔名應該是 001a-001a (現在是 01a-001a)

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.1.102

**Comment by chiehan1** [comment]
test ok in v0.1.102 in mac and windows8
thank you
