### ISSUE TITLE
windows8 undo pagebreak 之後，pagebreak 分頁點前面會缺一個字元

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#163]
mac 版正常
用 windows8 會出現影片的情形
影片從第一行的 123 分頁
undo pagebreak 之後
第一行 123 的 3 不見了
https://youtu.be/3J-GgPhL50s?t=10s

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.2.0

**Comment by chiehan1** [comment]
v0.2.0
windows 分頁點之前缺字的 bug 已 fix
但變成 mac 和 windows 版，如果分頁點有 line break 
 undo pagebreak 之後，這個 line break 會不見 #164
https://youtu.be/Lh-7WS1xxmM
