### ISSUE TITLE
如果分頁點有 line break，undo pagebreak 之後，這個 line break 會不見

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#164]
v0.2.0
windows 分頁點之前缺字的 bug 已 fix #163 
但變成 mac 和 windows 版，如果分頁點有 line break 
 undo pagebreak 之後，這個 line break 會不見
https://youtu.be/Lh-7WS1xxmM

**Comment by kmsheng** [comment]
@chiehan1 請試試看 v0.2.3, 我是用 win7 測的, 現在連滑鼠的位置都會復原

**Comment by chiehan1** [comment]
test ok in v0.2.3 in mac and windows8
thank you!
