### ISSUE TITLE
匯入 xml 檔時，如果有缺少後面引號 > 的 tag 時，希望能禁止匯入並有警示告知此錯誤 tag 是在哪一個檔案的哪一個 pb

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#165]
匯入 xml 檔時，如果有缺少後面引號 > 的 tag 時，
像是出現
<sutra
<sutra id=
<ttile =""
<stitle id="12"/
諸如此類的這種缺少 > 的 tags

希望能像 #128 一樣禁止匯入並有警示告知此錯誤 tag 是在哪一個檔案的哪一個 pb

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.2.4

**Comment by chiehan1** [comment]
出現缺少 > 的 tag，希望能禁止匯入並告知使用者這個錯誤 tag 在哪個檔案的哪個 pb，像是這些
<sutra
<sutra id=
<ttile =""
<stitle id="12"/

例如如果匯入的 hello.xml 檔內容是

<pb id="1.1a"/>
wrong tag in 1.1a
<sutra
<pb id="1.1b"/>
1.1b

就禁止匯入並告知使用者 hello.xml 的 1.1a 的 tag 有問題

匯入 world.xml 的內容是
<pb id="1.1a"/>
1.1a
<pb id="1.1b"/>
1.1b
<pb id="1.2a"/>
wrong tag in 1.2a
<stitle id="12"/
<pb id="1.2b"\/>
1.2b

禁止匯入並告知使用者 world.xml 的 1.2a 的 tag 有問題

**Comment by kmsheng** [comment]
@chiehan1 http://regexr.com/3d80h

**Comment by chiehan1** [comment]
http://regexr.com/3d80q
多找了
<

**Comment by kmsheng** [comment]
@chiehan1  還有 <stitle text</stitle> 的 case, 這種防呆案例我覺得沒完沒了
就一次在這個 issue 寫清楚吧
http://regexr.com/3d810

**Comment by chiehan1** [comment]
還有缺 < 的
text > text
< text > text > text

**Comment by chiehan1** [comment]
目前想到的有六種
<
text < text
text < text < text > text
>
text > text
text < text > text > text

**Comment by chiehan1** [comment]
因為還沒看過缺 < 的
缺 < 的情況有點離譜
抓太嚴謹可能會很難匯入
那麼就請先抓缺 > 的就好了
~~<~~ (這個不太可能發生，不用抓這種)
text < text
text < text < text > text

**Comment by kmsheng** [comment]
@chiehan1 請測看看目前的修正 v0.2.5

**Comment by chiehan1** [comment]
test ok in v0.2.5 in mac and windows8
thank you

**Comment by chiehan1** [comment]
除了之前寫的缺少 > 的 tag
如下列兩種
text < text
text < text < text > text

請新增下列這種缺少 > 的 tag 的錯誤訊息提示，提示此錯誤 tag 在哪個檔案的第幾頁
<stitle>།ཁྱིམ་བདག་ཅིག་གིས་སངས་རྒྱས</stitle

範例影片
https://www.youtube.com/watch?v=wuuIJtKxMjs&feature=youtu.be

測試檔
https://drive.google.com/open?id=0B7IngcS_Eo5JdE5aaWdzOXc3LU0

**Comment by kmsheng** [comment]
@chiehan1 hi, 已修正了. 請試試 v0.2.7

**Comment by chiehan1** [comment]
v0.2.7 os 和 windows 8 測試 ok
感謝
