### ISSUE TITLE
有些之前存的 document 無法 undo pagebreak

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#166]
如果把這個 document 重新 import zip 進 v0.2.3
zip 檔下載連結
https://drive.google.com/open?id=0B7IngcS_Eo5JVFYzUG1TQ0FzaGs
pagebreak 之後 
無法 undo pagebreak

但如果接著再把這個不能 pagebreak 的 document，export file with pb
把此 txt 副檔名改成 xml，加上原圖再次 import
這個新的 document 就能 undo pagebreak

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.2.4

**Comment by chiehan1** [comment]
test ok in v0.2.4 in mac and windows8
thank you
