### ISSUE TITLE
更新新的拼字檢查

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#167]
請更新新的拼字檢查模組
https://github.com/karmapa/checkTibetan_for_ketaka

**Comment by kmsheng** [comment]
@chiehan1 已更新在 v0.2.5

**Comment by chiehan1** [comment]
test ok in v0.2.5 in mac and windows8
這版修正了斷句符號 ༑ 的檢查
現在有這個符號不會標為錯字
