### ISSUE TITLE
開啟 find 視窗，切換 tab 時，希望 find 可以在每個 tab 運作

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#168]

**Comment by chiehan1** [comment]
v0.2.5
開啟 find 視窗，切到其他 tab 以後，find 功能就無法正常運作了
切回原本的 tab，find 仍無法運作
需要關掉 find 再重開
希望能像 sublime 的例子一樣，就算不關掉 find 視窗，切換每個 tab 時，find 都能搜尋當下 tab 的內容
https://youtu.be/D_Qxvo5QPXM

**Comment by kmsheng** [comment]
@chiehan1 fixed in v0.2.6

**Comment by chiehan1** [comment]
test ok in v0.2.6 with windows8 and os10.11.4
