### ISSUE TITLE
當 impoort 有問題的 zip 檔時，請告知使用者 zip 檔有問題

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#169]
測試檔
https://drive.google.com/open?id=0B7IngcS_Eo5JUGVMUDNFdzF5Vm8

有時使用者會直接到 doc 壓縮專案
直接壓縮 image 資料夾和 json 檔
所以壓縮檔外層沒有包一層資料夾

當 import 這樣的 zip 檔時，會出現 doc not create 的訊息 
請問是否能將錯誤訊息改為告知使用者 zip 檔有問題

![2016-05-24 6 06 49](https://cloud.githubusercontent.com/assets/13195099/15500242/786e484c-21da-11e6-98db-3d3d20effec1.png)

**Comment by kmsheng** [comment]
@chiehan1 hi, 已修正了. 請試試 v0.2.7

**Comment by chiehan1** [comment]
感謝
v0.2.7 os 和 windows8 測試 ok
