### ISSUE TITLE
更改排序檢查的 pb id 和 圖檔名稱

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#170]
之前的排序檢查 #83 

現在需要排序檢查 pb id 和圖檔名，有 4 種格式

數字-數字[abcd]
數字-數字-數字[abcd]
數字-數字
數字-數字-數字

pb id 和 圖檔名稱一致
# 

如果編號沒有 abcd

1-1, 1-2, 1-4
會警示
1-3 might be missing in 檔案名

1-1, 1-2, 1-5
會警示
1-3, 1-4 might be missing in 檔案名

1-1, 1-2, 1-3, 2-1
不會跳出警示

數字-數字-數字的檢查同上
1-1-1, 1-1-2, 1-1-3, 1-2-1, 2-1-1
不會跳出警示
# 

如果編號有 abcd

1-1a 1-1b 1-2a 1-3a 1-3b
會警示
1-2b might be missing in 檔案名

1-1a 1-1b 1-3a 1-3b
會警示
1-2a 1-2b might be missing in 檔案名

1-1a 1-1b 1-2a 1-2b 1-2c 1-3a 1-3b
會警示
1-2d might be missing in 檔案名

1-1a 1-1b 1-2a 1-2b 1-3a 1-3b 2-1a 2-2b
不會跳出警示

數字-數字-數字[abcd] 的檢查同上
1-1-1a 1-1-1b 1-1-2a 1-1-2b 1-1-3a 1-1-3b 1-2-1a 1-2-1b 2-1-1a 2-1-1b
不會跳出警示

目前是文字檔的 pb id 和 圖檔都缺才會跳出警示
# 

數字-數字 測試檔
http://goo.gl/p7KtkI
錯誤訊息 
1-3 might be missing in 1-1 text.xml

數字-數字-數字 測試檔
http://goo.gl/RndgKx
錯誤訊息
1-1-3 might be missing in 1-1-1 text.xml

數字-數字[abcd] 測試檔
http://goo.gl/DX7o3O
錯誤訊息
1-2a, 1-3a, 1-4b, 1-6a, 1-6b, 1-7c, 1-8d, 1-16b, 2-1d might be missing in 1-1a text.xml

數字-數字-數字[abcd] 測試檔
http://goo.gl/3rIuXp
錯誤訊息
1-1-2a, 1-1-3a, 1-1-4b, 1-1-6a, 1-1-6b, 1-1-7c, 1-1-8d, 1-1-16b, 1-2-1d might be missing in 1-1-1a text.xml

**Comment by chiehan1** [comment]
經由 11/10 技術組會議和之前決議，統一用三組數字的編碼，
所以只有下列兩種需排序檢查
數字-數字-數字(加abcd) 和 數字-數字-數字

加 abcd 的是木刻本會用，不加 abcd 的編號是近代紙本書籍會用到

**Comment by chiehan1** [comment]
重新製作 1-1-1 和 1-1-1a 兩種 pb id 格式的混合測試檔
https://drive.google.com/open?id=0B7IngcS_Eo5JdlpEZEdadktFMnc

錯誤訊息有下列 pb id 和其所在的檔案名或圖檔名
(1-2-2a, 1-2-3a) 
(1-2-3b, 1-2-4b)
(1-2-5c, 1-2-6a)
(1-2-6b, 1-2-6d)
(1-2-7b, 1-2-8c)
(2-1-1b, 2-3-1a)
(2-4-1b, 4-1-1a)
(4-1-1b, 5-1-6a)

(1-1-0, 1-1-2)
(2-1-1, 2-3-1)
(3-1-2, 5-1-1)
(5-1-2, 6-1-3)

**Comment by kmsheng** [comment]
fixed in 0.2.8

**Comment by chiehan1** [comment]
v0.2.8
蠻清楚的，感謝
test ok in macOS 10.12.1 and windows8.1

**Comment by chiehan1** [comment]
經過討論，David 提議把
1-2-2b might be missing in 1-2-2a.png
換成
Found file 1-2-2a.png, but page 1-2-2b is missing.

比較清楚

**Comment by chiehan1** [comment]
v0.2.9
test ok in macOS 10.12.1 and windows 8.1
thank you
