### ISSUE TITLE
希望能警示有圖無文和有文無圖的 pb id 

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#171]
匯入時, 如果 page 物件只缺少文字或只缺少圖片, 要提示使用者這些頁碼有缺文或缺圖

可用 #170 的測試檔，連結如下
https://drive.google.com/open?id=0B7IngcS_Eo5JdlpEZEdadktFMnc
應提示缺少 1-2-1a 的圖 和 1-2-1b 的文字

**Comment by kmsheng** [comment]
fixed in 0.2.8

**Comment by chiehan1** [comment]
test ok in macOS 10.12.1 and windows8.1
