### ISSUE TITLE
匯入 empty tag <> 的 xml 檔時，請告知使用者文件內有 empty tag <>

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#172]
v0.2.7
如果 xml 檔有 empty tag <>
錯誤訊息是 TypeError: Cannot read property 'name' of null
希望錯誤訊息明確讓使用者知道文件內有 <>

**Comment by kmsheng** [comment]
fixed in 0.2.8

**Comment by chiehan1** [comment]
test ok in macOS 10.12.1 and windows7
