### ISSUE TITLE
匯入有 empty tag <> 的 txt 檔時，請告知使用者文件內有 empty tag <>

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#173]
匯入有 empty tag <> 的 txt 檔時，請告知使用者文件內有 empty tag <> ~並禁止匯入~

**Comment by kmsheng** [comment]
fixed in 0.2.8

**Comment by chiehan1** [comment]
可以匯入 txt 檔但會警示有 empty tag <>

test ok in mac 10.12.1 and windows7
