### ISSUE TITLE
非空行之後貼文字，ketaka-lite 會停住很久

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#174]
v0.2.7

以 mac air 操作
在空行貼 50 行文字，沒問題
但在非空行之後貼文字，會停住約 30 秒
https://youtu.be/_PzHcH98e04

空行貼 5000 行文字會停住約 15 秒
非空行貼 5000 行文字停住的時間超過 2 分鐘，使用者以為當機

**Comment by kmsheng** [comment]
這個問題是因為在 render process 做歷史紀錄的操作, 所以會比較慢。
我把比較 heavy 的運算都搬到 main process 了。

目前處理五千行還沒問題, 如果超過這個行數還要順暢的話, history 可能要做某種取捨 ( 例如資料量大到一個程度就不處理 history )。

**Comment by kmsheng** [comment]
fixed in 0.2.8

**Comment by chiehan1** [comment]
v0.2.8 
macOS 10.12.1 測試

空行貼 50 行，順暢
非空行貼 50 行，改善許多，10 秒可以動
空行貼 5000 行 (100,000字元)，改善許多，停止約 4 秒以內
非空行貼 5000 行仍停頓許久
