### ISSUE TITLE
希望能縮短一次改變大量文字的停頓時間

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#176]
v0.2.7
使用者常一次改變幾千甚至幾萬行以上的文字資料

如：複製, 貼上, 剪下, 刪除等等

會有幾十秒到幾分鐘以上的停頓

希望能縮短停頓時間

**Comment by chiehan1** [comment]
測試環境
MacBook Air 10.12.1
1.6 GHz Intel Core i5
4 GB 1600 MHz DDR3

貼上 15000 行共 25 萬字元
hackpad 第 20 秒 顯示貼上的文字，第 40 秒游標可動
KETAKA-Lite v0.2.7 馬上顯示貼上的文字，第 90 秒游標可動

**Comment by kmsheng** [comment]
請看一下 0.2.8 是不是有好一點 ?

**Comment by kmsheng** [comment]
請看一下 0.2.8 是不是有好一點 ?

**Comment by chiehan1** [comment]
測試環境
MacBook Air 10.12.1
1.6 GHz Intel Core i5
4 GB 1600 MHz DDR3

貼上 15000 行共 25 萬字元
v0.2.7 約第 90 秒游標可動
v0.2.8 約 25 秒內游標可動
改善許多
