### ISSUE TITLE
圖片區右下角的圖檔資訊，在游標離開圖片區後，不會消失

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#177]
![group](https://cloud.githubusercontent.com/assets/13195099/19633545/8acc055a-99e5-11e6-8a41-033f92bf10ac.png)

**Comment by kmsheng** [comment]
@rickie120243 請志軒協助處理

**Comment by kmsheng** [comment]
fixed in 0.2.8

**Comment by chiehan1** [comment]
test ok in MacOS 10.12.1 and windows7
