### ISSUE TITLE
pb id 的排序希望能使用 natural sort

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#180]
測試檔連結
https://drive.google.com/open?id=0B7IngcS_Eo5JSmx3TGRqdTBxLXc

測試檔的 pb id 希望能維持以下排序
[1-1-1a, 1-1-1b,
 1-1-2a, 1-1-2b,
 1-1-10a, 1-1-10b,
 1-2-1a, 1-2-1b,
 1-10-1a, 1-10-1b, 
 2-1-1a, 2-1-1b,
 10-1-1a, 10-1-1b]

目前 v0.2.9 版本匯入後的排序會變成
[1-1-1a, 1-1-1b,
 1-1-10a, 1-1-10b,
 1-1-2a, 1-1-2b,
 1-10-1a, 1-10-1b, 
 1-2-1a, 1-2-1b,
 10-1-1a, 10-1-1b
 2-1-1a, 2-1-1b]

**Comment by kmsheng** [comment]
現在的 natural sort  node.js module ( https://www.npmjs.com/package/javascript-natural-sort ) ( .https://www.npmjs.com/package/natural-sort ) 都不能正確排序 pb ids, 所以這邊我自己修正了

請參考 0.2.10

**Comment by chiehan1** [comment]
test ok min macOS 10.12.1 and windows 8.1
