### ISSUE TITLE
點搜尋 bar 的 Ʌ V 按鈕沒反應

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#182]
v0.2.11
https://gfycat.com/ImperturbableFreshGossamerwingedbutterfly

![2017-09-06 4 08 11](https://user-images.githubusercontent.com/13195099/30101843-60851630-9320-11e7-8530-888e36ae7d9c.png)

**Comment by kmsheng** [comment]
@chiehan1 on what os ?

**Comment by chiehan1** [comment]
mac
windows 32 and 64 bits

**Comment by chiehan1** [comment]
已在 mac 和 windows 32bit, 64bit 確認
