### ISSUE TITLE
Two problems in Ketaka-Lite

### ISSUE THREAD

**Issue by zhandi100** [karmapa/ketaka-lite#21]
1.Tibetan EWTS can not type "ང"(nga)
2.Settings of Ketaka-Lite the cancel button is not working

Please take a look about these problems.Thank you!

**Comment by eroux** [comment]
For the first problem, [this patch](https://github.com/eroux/jquery.ime/commit/ea2a7bbe228b1a5842f377b196e50ae1d37bfdd4) should be applied. I'm quite amazed something as big as this went unnoticed until now... so thanks for the report!

**Comment by kmsheng** [comment]
https://drive.google.com/open?id=0B0sfHY8vpXYhSl9ibW9memx5Ums

Please try this one. Problems should be fixed.

**Comment by kmsheng** [comment]
reopen this issue if the problem still exists
