### ISSUE TITLE
圖片的放大縮小工具列和圖片路徑會重疊

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#22]
如圖黃色框框的地方，
當調整視窗大小後，  
圖片下方的 "放大縮小工具列" 和 "圖片路徑" 常常會重疊
重疊時沒有辦法調整圖片大小

![ketakaliteissue1](https://cloud.githubusercontent.com/assets/13195099/9951113/e48fd964-5df4-11e5-920b-6d4b773c5f65.jpg)

**Comment by kmsheng** [comment]
Thanks for reporting this issue.
Please try the fixed version below
https://drive.google.com/open?id=0B0sfHY8vpXYhT3J6ODFUT0gwUWc

If everything works fine, I am going to merge the fixed branch to master.

**Comment by kmsheng** [comment]
reopen this issue if the problem still exists
