### ISSUE TITLE
Another Tibetan EWTS typing problem

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#23]
When using Tibetan EWTS input method,  the following syllables can't be typed:
1. རྔ (rnga) : also རྔེ (rnge) རྔོ (rngo) རྔུ (rngu)  
2. རྙ (rnya) : also རྙེད (rnyed) རྙི (rnyi) རྙོག (rnyog) 
3. ལྔ (lnga) :

**Comment by eroux** [comment]
Thanks for testing! It should be fixed in [this file](https://github.com/eroux/jquery.ime/blob/fix-ewts/rules/bo/bo-ewts.js) by [this commit](https://github.com/eroux/jquery.ime/commit/f7a2d4892dbe24fd8a3c2921f9a26c8e609483b6)

**Comment by kmsheng** [comment]
@chiehan1 eroux's patch has been appled, please download v0.1.3.zip and try again.

**Comment by chiehan1** [comment]
Already tried it. It's ok! Thank you Elie and David!

**Comment by eroux** [comment]
Not really related to this issue, but @kmsheng , maybe you could also import the new sambhota input method from [my repo](https://github.com/eroux/jquery.ime/blob/bo-sambhota/rules/bo/bo-sambhota.js), it's been recently approved by the Tibetan consultant (after many attempts).

**Comment by kmsheng** [comment]
@eroux ok, I am doing it now : ) been busy in the past few days

**Comment by kmsheng** [comment]
done.

**Comment by eroux** [comment]
thanks!
