### ISSUE TITLE
The moved picture didn't return to the middle of the window after setting its size to 100%.

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#24]
At first, I enlarged the picture to 125% and change its position to the right.
![sample2](https://cloud.githubusercontent.com/assets/13195099/10011242/ec61ce44-6129-11e5-9886-e81b5311da57.jpg)

but when I set the picture size to 100%, it doesn't return to the middle place, and I can't move it either.
![sample3](https://cloud.githubusercontent.com/assets/13195099/10011246/f534e862-6129-11e5-87ce-d82556bd7c8b.jpg)

**Comment by kmsheng** [comment]
@chiehan1 fixed, please try v0.1.4.

**Comment by chiehan1** [comment]
Already checked the fixed version! It's ok! Thank you!!
