### ISSUE TITLE
字距的問題

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#25]
letter spacing設為1的字距仍然太寬
圖一
![sample4](https://cloud.githubusercontent.com/assets/13195099/10012189/cac9c666-6137-11e5-84ec-e1b14d7661d7.jpg)

下圖是理想的字距
圖二
![sample1](https://cloud.githubusercontent.com/assets/13195099/10012192/db68fa50-6137-11e5-93f5-76bb98dc7a78.jpg)

不知能否把 letter spacing 1 的字距調整為圖二的字距
而letter spacing 最寬的字距設為目前v0.1.3圖一的 letter spacing 1的字距即可
因此字距的可選擇範圍調整為，從圖二的字距(最窄) 到圖一的字距(最寬) 
另外letter spacing 的下拉式選單不用分為 30 組那麼多組，可能的話，組數可以分為少數例如五組即可

**Comment by kmsheng** [comment]
@chiehan1 fixed, please try v0.1.4.

**Comment by chiehan1** [comment]
David您好：
請問letter spacing 1的字距不知是否能再縮減為現在v0.1.4的三分之二，letter spacing 2、3、4的間隔再依比例調整，letter spacing 5不變，感謝!

**Comment by kmsheng** [comment]
@chiehan1 我來解釋一下  https://github.com/karmapa/ketaka-lite/commit/73b55b7764b15ba05cd94c4f5678c0c6aae0fb38 _editor.scss 的修改做了什麼, 
上面 _editor.scss 的迴圈會產生 .ls1 ~ .ls5 的 css class, 對應的值分別為 0.05em, 0.1em ... 一直到 0.25em

em 是相對單位, 套用上去的實際數值要乘上 element 本身的 font size, 假設目前套用的是 的 14px
0.05em 的字距套用上去就會是 0.7px, 整個區間就會是 0.7px, 1.4px ... 一直到 3.5px

**Comment by kmsheng** [comment]
@chiehan1 套用上面的描述就會是 ( i \* 0.054125 ) - 0.020625
5 不變, 故 5 為 0.25em
1 為 2/3 倍, ≒ 0.0335em
0.0335em, 0.087625em ... 0.25em

**Comment by kmsheng** [comment]
@chiehan1 請 chiehan1 確認一下, 沒問題我再改程式

**Comment by chiehan1** [comment]
是的，沒錯，感謝您!!
因為沒有辦法測量老師給我的上面圖二的字距，目前只能粗略估計他要求的寬度，ls1大概再縮減成現在的2/3倍，ls2,3,4照著間隔比例調，間隔是0.0335em, 0.087625em ... 0.25em沒錯，希望這次能符合老師要求的字距。
不好意思麻煩您了!!

**Comment by kmsheng** [comment]
@chiehan1 please try v0.1.5.zip

**Comment by chiehan1** [comment]
David您好，因為勘布覺得還是太寬，再麻煩您改成 0.015em, 0.0335em, 0.075em,  0.1125em, 0.15em，感謝!!

**Comment by kmsheng** [comment]
should be fixed by https://github.com/karmapa/ketaka-lite/pull/46
