### ISSUE TITLE
The Ketaka-Lite window in Mac OS system has a bug.

### ISSUE THREAD

**Issue by zhandi100** [karmapa/ketaka-lite#26]
I can not restart Ketaka-Lite window after it had closed.

Just this problem in Mac OS.

Thank you !

**Comment by kmsheng** [comment]
Make sure KETAKA-Lite is absolutely closed, closing window doesn't mean you close the whole application. 
Take a look at top-left corner for KETAKA_Lite / Quit.

We can discuss about the default closing behavior for mac, too.
This can be changed.

**Comment by kmsheng** [comment]
@zhandi100 hi, did you read my comment ?

**Comment by chiehan1** [comment]
What Run means is that when you close the window on Mac, you cannot reopen it from the dock. You have to terminate the program before you can reopen the window. This is not a normal Mac behaviour as in other software we can reopen the window after it's close, don't necessarily need to terminate the software.

Allen

**Comment by kmsheng** [comment]
Ok, Allen. I got your point.
I am now making the program to be terminated whenever the window is closed.

**Comment by kmsheng** [comment]
since we aren't designing multi-window application, I think this behavior is not necessary.

**Comment by zhandi100** [comment]
Sorry, I busied recently. I understand what you mean, then please make it like Note application on Mac that is a single-window application. When clicking the close button it will terminate the software.

Thank you !

**Comment by kmsheng** [comment]
@zhandi100 please try v0.1.5.zip

**Comment by zhandi100** [comment]
Already checked it! It's solved! Thank you!!
