### ISSUE TITLE
ketaka-lite mac版本 文字無法從外面檔案複製貼上

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#28]
如題

**Comment by kmsheng** [comment]
I can't reproduce this issue, please provide more details.

**Comment by chiehan1** [comment]
we can't replicate, cut, and paste text or sentences between the pages in ketaka_lite, and we can't replicate, cut, and paste text or sentence from other text files to ketaka_lite directly either(not through import), the hotkey and the right click of mouse to replicate, cut, and paste seems to be blocked in ketaka-lite.

**Comment by kmsheng** [comment]
@chiehan1 did you try shortcut command + c and command + v ?  be sure that you weren't using ctrl key on mac platform

**Comment by chiehan1** [comment]
yes, I have tried command +c and command + v, it didn't work in our mac, and I didn't press the ctrl key at the same time, if this situation is not the same as yours, maybe we can leave this issue and discuss it after the meeting on next Tuesday.
Thank you so much!!

**Comment by kmsheng** [comment]
ok, I now reproduce the problem

**Comment by kmsheng** [comment]
reported this issue to official electron
https://github.com/atom/electron/issues/2959

**Comment by kmsheng** [comment]
@chiehan1 please try v0.1.6

**Comment by chiehan1** [comment]
It's ok! Thank you so much!
And please add replicate, cut, and paste function through mouse right click button in both Mac and Windows version, for many users don't use the shortcut like command x,command c, and command v

**Comment by kmsheng** [comment]
@chiehan1 This should be reported as another issue. I created one for you.
https://github.com/karmapa/ketaka-lite/issues/32
