### ISSUE TITLE
mac版 輸入文字後 常常無法換頁

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#29]
import純圖檔的資料夾後，輸入文字
有時輸入1行藏文或英文後就無法換頁
有時輸入多行後無法換頁
有時輸入超過6行後才無法換頁
但有時輸入超過6行仍然可以換頁

**Comment by kmsheng** [comment]
@chiehan1 fixed, please try v0.1.4.

**Comment by chiehan1** [comment]
Already checked it! It's solved! Thank you!!
