### ISSUE TITLE
windows版 import資料夾 吃不到正確圖檔

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#30]
David您好

我用的純圖片資料夾如下 import時appdata的ketaka-lite檔案已清空
https://drive.google.com/open?id=0B7IngcS_Eo5JeUltdDlSR3FRWFk
![sample5](https://cloud.githubusercontent.com/assets/13195099/10016706/8a9e56dc-615b-11e5-8280-d27587181b1d.jpg)
import 之後會顯示讀到tiff檔，但我的檔案應該都是jpg檔＿
![sample6](https://cloud.githubusercontent.com/assets/13195099/10016723/b19c0040-615b-11e5-9373-6764eda8555f.jpg)
之後只會讀到幾張圖檔，後面的圖檔都讀不到，而且讀不到csv檔內的圖檔名
![sample7](https://cloud.githubusercontent.com/assets/13195099/10016743/c93831ce-615b-11e5-9388-e47f1f5ff0f2.jpg)
![sample8](https://cloud.githubusercontent.com/assets/13195099/10016746/cbf35a56-615b-11e5-9f77-b38c3cfa6689.jpg)
請問我的操作是否有問題呢?
感謝

**Comment by kmsheng** [comment]
Your've done it right and those images were actually TIFF for sure.
[This](https://en.wikipedia.org/wiki/Magic_number_%28programming%29#Magic_numbers_in_files) is how I checked the file types. Reopen this issue if you have futher more questions related to this issue.
