### ISSUE TITLE
problem of page order after import a folder

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#31]
Hello David!

I import this file  in windows version
dulwa_v0.1.5test.rar  https://drive.google.com/open?id=0B7IngcS_Eo5JeUltdDlSR3FRWFk

and the page is not ordered. (not from 1.1a, 1.1b, 1.2a ... to 1.10b)

Did I do something wrong? 
Thank you!

**Comment by chiehan1** [comment]
the imported order is dulwa-001-006a, dulwa-001-010b, dulwa-001-010a, dulwa-001-006b, dulwa-001-001a, dulwa-001-007a, dulwa-001-002b, dulwa-001-002a, dulwa-001-01b, dulwa-001-08a, dulwa-001-03b, dulwa-001-03a, dulwa-001-04a, dulwa-001-04b, dulwa-001-05a, dulwa-001-05b, dulwa-001-07b, dulwa-001-08b, dulwa-001-09a, dulwa-001-09b

and my expected order is , dulwa-001-001a, dulwa-001-01b, dulwa-001-02a, dulwa-001-02b, dulwa-001-03a, dulwa-001-03b, dulwa-001-04a, dulwa-001-04b, dulwa-001-05a, dulwa-001-05b, dulwa-001-06a, dulwa-001-06b, dulwa-001-07a, dulwa-001-07b, dulwa-001-08a, dulwa-001-08b, dulwa-001-09a, dulwa-001-09b, dulwa-001-010a, dulwa-001-010b

**Comment by kmsheng** [comment]
@chiehan1 fixed, please try v0.1.8

**Comment by chiehan1** [comment]
I have tried the windows version, it's perfect! 
And I will get the computer in mac system in office tomorrow, then try mac version. Thank you so much!!

**Comment by chiehan1** [comment]
mac version is also ok, thank you.

**Comment by chiehan1** [comment]
In mac v0.1.14, after import, some of the page orders is not ordered, it's like 1.x and 2.x will arrange by turns in example1 and example2 below
1. the page order of this folder below will be 1.269b, 2.1a, 1.1b, 1.2a 1.2b,1.3a, 1.3b, 1.4a, 1.4b, 1.5a,1.5b, 1.6a,1.6b, 1.7a, 1.7b, 1.8a, 1.8b, 1.9a, 1.9b, 1.10a, 1.10b, 1.11a,1.11b, 1.12a, 2.1b, 2.2a, 2.2b.........
   https://drive.google.com/open?id=0B7IngcS_Eo5JOEZIQTBneXMwMmc
2. the page order of this folder will be 1.1b, 1.2a, 1.2b, 2.0a, 2.0b, 2.1a, 2.1b, 2.2a, 2.2b, 2.3a, 1.3a......
   https://drive.google.com/open?id=0B7IngcS_Eo5JQzNnWmJLWGdmc1k
3. the page order of this folder is dulwa-001-001b, dulwa-001-005b, dulwa-001-005a, dulwa-001-002a, dulwa-001-002b, dulwa-001-003a, dulwa-001-003b, dulwa-001-004a, dulwa-001-004b, dulwa-001-001a, dulwa-001-006a.......
   https://drive.google.com/open?id=0B7IngcS_Eo5JeldtNmcyMkxFRU0

Would you please check these problem? Thank you!!

**Comment by kmsheng** [comment]
fixed in  v0.1.20

**Comment by chiehan1** [comment]
Hello David!
I have tried v0.1.22 in windows version
the page order is ok with this folder, the files in this folder are named in the form of "001-001a"
https://drive.google.com/open?id=0B7IngcS_Eo5JNVBDQzI2YVlSZ00

but the page order of these two folders are not ok
the files of this folder are named by "01" "02" "03"...
https://drive.google.com/open?id=0B7IngcS_Eo5JOWRXZDRweUdKZGc

and these "dulwa-001-001a"...
https://drive.google.com/open?id=0B7IngcS_Eo5JQ195SWVyd1hVbEk

**Comment by chiehan1** [comment]
except for test files in last comment, 法海師 import this folder and the page order is wrong too 
https://drive.google.com/open?id=0B7IngcS_Eo5JbG9uZFN0QVpNSXc

**Comment by kmsheng** [comment]
@chiehan1 https://drive.google.com/file/d/0B7IngcS_Eo5JQ195SWVyd1hVbEk/view
這裡面的格式 (dulwa-001-001a.jpg) 是怎麼回事? 後來不是說好採用 https://github.com/karmapa/ketaka-lite/tree/master/files/samples/b/images ( 003-001b.jpg ) 嗎?

**Comment by kmsheng** [comment]
https://drive.google.com/open?id=0B7IngcS_Eo5JbG9uZFN0QVpNSXc 這裡面的格式也沒講好啊

**Comment by chiehan1** [comment]
David您好：

我有轉寄法海師給您的圖檔命名規則到email信箱

圖檔有兩類：
A.貝葉經圖檔依001-001a.jpg,001-001b.jpg......格式命名
B.書籍圖檔依001-0001.jpg, 001-0002.jpg,.....or
                    0001.jpg, 0002.jpg......or
                    1.jpg, 2.jpg.......

**Comment by kmsheng** [comment]
new sorting algorithm has beed applied in v0.1.25

**Comment by chiehan1** [comment]
it's all ok!!
Thank you very much!!
