### ISSUE TITLE
Add copy / cut / paste through right click menu

### ISSUE THREAD

**Issue by kmsheng** [karmapa/ketaka-lite#32]

**Comment by kmsheng** [comment]
this will be applied in v0.1.11

**Comment by chiehan1** [comment]
sorry, I didn't put the image to this issue, still can't use mouse right click menu to copy, cut, and paste as this image on v0.1.11
![copypaste](https://cloud.githubusercontent.com/assets/13195099/10689611/3017837a-79af-11e5-978a-17dddccd2725.jpg)

**Comment by kmsheng** [comment]
i don't have that problem on my windows7 laptop, what's wrong with yours?
have u tried v0.1.13 ?

**Comment by chiehan1** [comment]
I tried v0.1.14, it's ok, thank you
