### ISSUE TITLE
Move doc settings button to the rightmost of the toolbar

### ISSUE THREAD

**Issue by kmsheng** [karmapa/ketaka-lite#41]

**Comment by kmsheng** [comment]
This would be applied in v0.1.11

**Comment by chiehan1** [comment]
sorry I didn't put the image, please move to the rightmost as the image below, thank you
![default](https://cloud.githubusercontent.com/assets/13195099/10688743/01992da6-79a9-11e5-89f0-fa1160491804.JPG)

**Comment by kmsheng** [comment]
this should fixed in v0.1.14
