### ISSUE TITLE
Add print button

### ISSUE THREAD

**Issue by kmsheng** [karmapa/ketaka-lite#42]
Should be able to print single page or the whole bamboo

**Comment by kmsheng** [comment]
@chiehan1  Tested. Printing single page or multiple pages is available with limited document size ( word count ).
It's not able to print the pages of given example bamboo.

**Comment by kmsheng** [comment]
Trying to convert text to image to resolve this problem, but this generates another cross platform graphic library issue.

**Comment by kmsheng** [comment]
https://github.com/y-a-v-a/node-gd # not work on windows

**Comment by kmsheng** [comment]
fixed in v0.1.35

**Comment by chiehan1** [comment]
@lamalien and @g1ahsia decide not to add print button in this version, cuz in window system, options for selecting printing range depends on users' printer software
