### ISSUE TITLE
Doc name 無法使用+-_符號命名

### ISSUE THREAD

**Issue by lamalien** [karmapa/ketaka-lite#47]
![ketaka_lite_issue_1_10192015](https://cloud.githubusercontent.com/assets/5266492/10595135/30873422-7707-11e5-8b68-d84a6ecb0cc2.jpg)

**Comment by kmsheng** [comment]
@lamalien  
I'd add dash (-) for you, but other characters are not welcome.
It has to be safe directory name and filename
https://support.microsoft.com/en-us/kb/905231

**Comment by kmsheng** [comment]
change will be applied for the next release
