### ISSUE TITLE
Doc rename之後視窗無法自動關閉

### ISSUE THREAD

**Issue by lamalien** [karmapa/ketaka-lite#48]
![ketaka_lite_issue_10_19102015](https://cloud.githubusercontent.com/assets/5266492/10595172/93c13272-7707-11e5-8ed9-8bcf1a71b127.png)

**Comment by kmsheng** [comment]
@lamalien 請問是哪個視窗?

**Comment by kmsheng** [comment]
checked with iamallen, was saving slow with large document
