### ISSUE TITLE
After export, we import the json on the other pc, but no text file show.

### ISSUE THREAD

**Issue by lamalien** [karmapa/ketaka-lite#55]
![ketaka_lite_issue_9_19102015](https://cloud.githubusercontent.com/assets/5266492/10595405/3a5587a8-770a-11e5-867f-f4553b4b5224.png)

**Comment by kmsheng** [comment]
@lamalien 
Would you upload your json to google drive or someehre else, so I can reproduce this issue ?

**Comment by chiehan1** [comment]
When exporting a bamboo as a zip file, the users have to unzip it, then put it in ~/Library/Application Support/ketaka-lite/docs and use "open" to select the bamboo, users can't import the zip file or the unzipped json file directly in other folders and they only can import the unzipped images without text.

**Comment by kmsheng** [comment]
No. This is wrong. Zip files are not supposed to be opened by users.
I've fixed the zip importing bug in https://github.com/karmapa/ketaka-lite/commit/e5296994f4b0574a179fee5615aa0b46e3838e7b
which is v0.1.16

**Comment by chiehan1** [comment]
I tried v0.1.17 in windows version, 
when I imported this folder with a zip exported earlier,
https://drive.google.com/open?id=0B7IngcS_Eo5JUkJJTHpjTTFrLVk
![zip1](https://cloud.githubusercontent.com/assets/13195099/10747914/943c091e-7c95-11e5-8f39-63dc7d0bdc8c.jpg)

it shows "TypeError cannot read property 'length' of undefined".
![zip2](https://cloud.githubusercontent.com/assets/13195099/10747918/9ed51a96-7c95-11e5-8703-04950c371791.jpg)

**Comment by kmsheng** [comment]
will be fixed in next release
https://github.com/karmapa/ketaka-lite/commit/ac4ea9e4f68ea18046395ff702f33a22940ba3e5

**Comment by kmsheng** [comment]
Add Export Zip in application menu, please try that in v0.1.18
