### ISSUE TITLE
when "find" the tibetan letter is dislocation.

### ISSUE THREAD

**Issue by lamalien** [karmapa/ketaka-lite#57]
![ketaka_lite_issue_11-1_10212015](https://cloud.githubusercontent.com/assets/5266492/10637441/57105808-7838-11e5-8a10-e3660cc8888d.png)
![ketaka_lite_issue_11_10212015](https://cloud.githubusercontent.com/assets/5266492/10637460/675ea304-7838-11e5-9c21-8775c31ae260.png)

**Comment by kmsheng** [comment]
@lamalien 這邊可能要判斷如果有組合成一個字的字元不能被拆開來 highlight
@yapcheahshen cc 葉老師

**Comment by chiehan1** [comment]
this situation only occurs in mac version，not in windows

**Comment by kmsheng** [comment]
fixed in v0.1.44
