### ISSUE TITLE
合併Find & Replace 會比較方便

### ISSUE THREAD

**Issue by lamalien** [karmapa/ketaka-lite#58]
![ketaka_lite_issue_12_10212015](https://cloud.githubusercontent.com/assets/5266492/10638229/6fbccef0-783c-11e5-91fe-8e5c259a7bba.png)

**Comment by chiehan1** [comment]
except for hot key, please add button or add the function to pull-down edit menu like undo, redo, copy, etc.

**Comment by kmsheng** [comment]
@chiehan1 please open that for a separated issue, i don't think they're relevant

**Comment by kmsheng** [comment]
Close this issue since find & replace are design to be separated in this project.
