### ISSUE TITLE
Add new page 時必須可以選擇Add  before Current page or After Current page.

### ISSUE THREAD

**Issue by lamalien** [karmapa/ketaka-lite#59]
![ketaka_lite_issue13_10212015](https://cloud.githubusercontent.com/assets/5266492/10638891/d2815594-783f-11e5-9e38-d5f8aae93a1c.png)

**Comment by kmsheng** [comment]
@lamalien 不太懂 ? 新增完頁面是會依照名稱下去排序的

**Comment by kmsheng** [comment]
已與法海師於 skype 確認
