### ISSUE TITLE
simplify pagebreak steps at the last page

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#62]
there are four steps when pagebreak at the last page:
1.add new page first
![pagebreak2](https://cloud.githubusercontent.com/assets/13195099/10684127/768dab50-797c-11e5-942b-69c675b3883c.JPG)
2.show new page
![pagebreak3](https://cloud.githubusercontent.com/assets/13195099/10684179/debc0474-797c-11e5-98cc-4025c79bc16c.JPG)
3.go back to the previous page
4.ctrl + enter to pagebreak
![pagebreak4](https://cloud.githubusercontent.com/assets/13195099/10684289/d7711456-797d-11e5-84e0-70ef301a5c45.JPG)

we can simplify the steps to:
1.ctrl + enter to pagebreak
![pagebreak4](https://cloud.githubusercontent.com/assets/13195099/10684289/d7711456-797d-11e5-84e0-70ef301a5c45.JPG)
2.show add new page directly
![pagebreak2](https://cloud.githubusercontent.com/assets/13195099/10684344/66722e24-797e-11e5-82cf-c65a9f56cd88.JPG)
3.press add new page button then the pagebreak text move to new page at the same time
![pagebreak2 -](https://cloud.githubusercontent.com/assets/13195099/10684337/4fee3a76-797e-11e5-97ab-987a8b4b8bfd.JPG)

**Comment by kmsheng** [comment]
@chiehan1 You can't guarantee that new page will be exactly be added to the last page.
It depends on page name order. If you add another "page name of last page" checking on input will make user confusing somehow.

**Comment by chiehan1** [comment]
ok, after discussion with user again, we think it's better to keep the present procedure, doesn't need to simplify it.
