### ISSUE TITLE
color of highlight can change to light-green and blue

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#64]
We can use use light-green to highlight results of spell-check, find, and replace instead of yellow,
and use blue instead of dark-yellow(grey-yellow?) to highlight "find next(or previous)", "replace next", and "next(or previous) wrong word" in spell-check.
As shown in the picture below:  
![highlightcolor](https://cloud.githubusercontent.com/assets/13195099/10721887/4eef1870-7be5-11e5-824a-9aceb84066dd.jpg)
Cuz the yellow color is too bright and many people feel it's harsh to the eye.

**Comment by kmsheng** [comment]
fixed in v0.1.17
