### ISSUE TITLE
find and replace button on the tool bar

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#65]
Please add find and replace button on the tool bar. Thank you David!! 
![replacebutton](https://cloud.githubusercontent.com/assets/13195099/10722177/60c80ffe-7be8-11e5-84ae-a6b4edadfa18.jpg)

**Comment by kmsheng** [comment]
Nope, too many buttons on toolbar. I would like to add it on application menu like what google chrome does.

**Comment by kmsheng** [comment]
will be added in v0.1.15
