### ISSUE TITLE
stop button in replace bar doesn't work

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#69]
I tried windows v0.1.22, when click the "stop" button, the replace tool bar is still there
![replace_stop](https://cloud.githubusercontent.com/assets/13195099/10780020/8f7b6b16-7d73-11e5-8cd1-095c77b00469.jpg)

**Comment by kmsheng** [comment]
fixed in v0.1.23

**Comment by chiehan1** [comment]
it's ok 
Thank you
