### ISSUE TITLE
the background color of line turns to black in default theme

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#70]
in v0.1.24 windows version
steps
1. open ketaka-lite and use Zenburn theme in settings
2. close ketaka-lite
3. re-open ketaka-lite (now ketaka-lite is in Zenburn theme)
4. turns Zenburn to default theme
then as shown in figure below
![setting1](https://cloud.githubusercontent.com/assets/13195099/10808955/183bf728-7e2c-11e5-8c7e-1817ba71508d.JPG)

this problem won't happen when opening ketaka-lite in default theme

**Comment by kmsheng** [comment]
fixed in v0.1.26

**Comment by chiehan1** [comment]
In windows v0.1.45, 
steps
1. open ketaka-lite and use Zenburn theme in settings
2. close ketaka-lite
3. re-open ketaka-lite (now ketaka-lite is in Zenburn theme)
4. click tab to create an empty bamboo
![123](https://cloud.githubusercontent.com/assets/13195099/11142487/99aa24a8-8a28-11e5-9bf3-408e6b529680.jpg)

**Comment by kmsheng** [comment]
fixed in v0.1.46
