### ISSUE TITLE
the scroll bar disappear after setting theme

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#71]
in windows v0.1.27
step1 
open setting window, the scroll bar exist
![settingquiet1](https://cloud.githubusercontent.com/assets/13195099/10836778/9c2ffde8-7eec-11e5-8e12-1b6bd1f771d3.jpg)
step2
change the theme, and the scroll bar disappear, and can't click the "close" button
so can't close the setting window
![settingquiet2](https://cloud.githubusercontent.com/assets/13195099/10836783/a14d6838-7eec-11e5-9cf5-0c49012633a0.jpg)

**Comment by kmsheng** [comment]
fixed in v0.1.28
