### ISSUE TITLE
spell-check finds many correct words 

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#72]
in windows KETAKA-Lite-win32-ia32-hunspell-bo
![spellcheck1](https://cloud.githubusercontent.com/assets/13195099/10840913/5803c13a-7f1f-11e5-85bd-dd1b608e0f6e.JPG)

**Comment by chiehan1** [comment]
In KETAKA-Lite-win32-ia32-hunspell-bo-2

we use ་  །  ༏  ༐  ༑  ༈  ཿ ༼   ༽ and space to split tibetan words

step1 put a paragragh on ketaka-lite and spellcheck
then all words are highlight as wrong spelling 
![spellcheck3](https://cloud.githubusercontent.com/assets/13195099/10843008/0e8b9192-7f31-11e5-9efe-edcc720bc038.jpg)

step2 split every word to 1word/1line
then no word is highlight as wrong spelling
![spellcheck4](https://cloud.githubusercontent.com/assets/13195099/10843015/1382f4a6-7f31-11e5-8ea6-2b49917c85b4.jpg)

step3 add ་ or ། in front of the words
and every word is highlight again
![spellcheck5](https://cloud.githubusercontent.com/assets/13195099/10843018/1bad5518-7f31-11e5-8717-a06c121e5f12.jpg)

does it mean that inside ་ or ། or other symbol we used, every word will be highlight as wrong spelling? 

and my text for test is 
དག་རབ་བཅད་ཅིང་། །མུ་སྟེགས་ཚོགས་རྣམས་ཐམས་ཅད་རབ་བཅོམ་སྟེ། །སྡེ་དང་བཅས་
པའི་བདུད་རྣམས་ངེས་བཅོམ་ནས། །བྱང་ཆུབ་འདི་བརྙེས་དེ་ལ་ཕྱག་འཚལ་ལོ། །ཁྱིམ་དོན་ཆེ་
ཆུང་སྤངས་ཏེ་དང་པོ་རབ་འབྱུང་དཀའ། །རབ་བྱུང་ཐོབ་ནས་ཡུལ་སྤྱད་དག་གིས་དགའ་ཐོབ་དཀའ། །
མངོན་དགའ་ཇི་བཞིན་དོན་བསྐྱེད་ཡང་དག་བྱེད་པ་དཀའ། །ངུར་སྨྲིག་གོས་འཆང་མཁས་པ་ཚུལ་
ལས་ཉམས་པ་དཀའ། །གཞི་རྣམས་ཀྱི་སྤྱི་སྡོམ་ལ། རབ་འབྱུང་གསོ་སྦྱོང་གཞི་དང་ནི། །

**Comment by kmsheng** [comment]
Close this issue due to https://github.com/karmapa/ketaka-lite/issues/61#issuecomment-153261570
