### ISSUE TITLE
export txt with pb, one space is added to pb tag and one empty line added to every page

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#73]
when import xml with correct pb tag. 
for example 
<pb id="1.1a"/> (the left of the figure)
there will be an empty line added to the end of every page (the middle of the figure)
when export file as a txt with pb, a space is added in the pb tag. 
for example
<pb id="1.1a" /> 
the splace is between <pb id="1.1a" and /> 
and there is also an additional empty line at the end of every paragraph
![import_export_content_form](https://cloud.githubusercontent.com/assets/13195099/10843685/47a3afa6-7f35-11e5-86e9-7fed94d72fae.jpg)

**Comment by kmsheng** [comment]
@chiehan1 Adding a space between double quotes and slash makes code more readable.
 If this breaks other systems when importing, I'd be happy to change that.

**Comment by chiehan1** [comment]
Yes, @lamalien let me to told you this, please change it, thank you!

**Comment by kmsheng** [comment]
fixed in 0.1.29
