### ISSUE TITLE
in search function, finding next will skip the target letter on the current page and jump to the next page then highlight by the position of some "finded letter"

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#74]
v0.1.31 in windows system
step1 type "a" in the search input window and it find "a" at line 1
![search1](https://cloud.githubusercontent.com/assets/13195099/10900877/44d5bb32-8220-11e5-8e38-2ec0f638709b.jpg)
step2 reposition the cursor and click "find next button"
![search2](https://cloud.githubusercontent.com/assets/13195099/10900878/44d75230-8220-11e5-8d41-8916357ba7a4.jpg)
step3 it skip the "a" at line 1 and highlight the "a" at line 2 directly
![search3](https://cloud.githubusercontent.com/assets/13195099/10900879/44d78ab6-8220-11e5-9c1e-5cbd0bbae9e5.jpg)
step4 reposition the cursor again and click "find next button"
![search4](https://cloud.githubusercontent.com/assets/13195099/10900880/44d7cf08-8220-11e5-9977-957a20502b98.jpg)
step5 it skip the "a" in the current page(page1) and highlight the "9" in the next page(page2)
![search5](https://cloud.githubusercontent.com/assets/13195099/10900875/44cb0ebc-8220-11e5-8aff-e984e4f243e5.jpg)
step6 click the "find previous button" twice, it jump to page 1 and highlight the "8" in page 1
![search6](https://cloud.githubusercontent.com/assets/13195099/10900876/44d03cc0-8220-11e5-8b01-b2f2516923cf.jpg)

**Comment by kmsheng** [comment]
Will be fixed in next release

**Comment by chiehan1** [comment]
find next "a" in page1 and keep click find next
![find11](https://cloud.githubusercontent.com/assets/13195099/10958851/6452c610-83ad-11e5-83fc-94ade5579ef2.jpg)
it highlight "2" in page2
![find12](https://cloud.githubusercontent.com/assets/13195099/10958853/66be1954-83ad-11e5-8e40-d174dfb0b08b.jpg)

**Comment by kmsheng** [comment]
fixed in v0.1.36
