### ISSUE TITLE
cannot find next letter when there is no matched letter on the next page but on other pages

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#75]
step1 on page2, click "find next button", but cannot progress if no "a" on the next page (page3)
![search7](https://cloud.githubusercontent.com/assets/13195099/10901289/c0e458fe-8226-11e5-81a8-6c9b00ce2b76.jpg)
step2 users have to move to the next page(page3) and click "find next button", so they can progress to next page(page4) if there is "a" on the next page(page4)
![search8](https://cloud.githubusercontent.com/assets/13195099/10901290/c23a0e74-8226-11e5-966b-185c085d4ebd.jpg)
step3 but after users move to page4 by clicking the "find next button", no "a" is highlighted by the grey color and the "find next button" doesn't work
![search9](https://cloud.githubusercontent.com/assets/13195099/10901291/c3b75cca-8226-11e5-9044-3ba4d705800f.jpg)
step4 click "find previous button" and it find the last "a" in page4, then keep click "find previous" several times, you will find it doesn't work again because there is no "a" on page3 
![search91](https://cloud.githubusercontent.com/assets/13195099/10901295/c55240f4-8226-11e5-8484-7c032e4dcfc9.jpg)

**Comment by kmsheng** [comment]
This is feature. Index of a search target is treated as an individual item.
