### ISSUE TITLE
After changing word color and saving, then re-open the same bamboo, many functions failed

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#79]
In windows, v0.1.39., after changing word color and saving the bamboo, then re-open it, 
search, replace, spellcheck, open other bamboo, tab to adding new bamboo, change word color are failed.  
![wordcolor1](https://cloud.githubusercontent.com/assets/13195099/10990708/16edf450-8491-11e5-8bde-3d02191c7b9c.jpg)

**Comment by kmsheng** [comment]
fixed in v0.1.40
