### ISSUE TITLE
print result with "print" mark

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#81]
![printmark](https://cloud.githubusercontent.com/assets/13195099/10994084/ea3a7438-84ae-11e5-86d3-177f15034e0a.jpg)

**Comment by chiehan1** [comment]
the print preview shows a print mark too 
![print2 -](https://cloud.githubusercontent.com/assets/13195099/10994186/adf6e974-84af-11e5-85ff-1faf250ee21b.jpg)

**Comment by kmsheng** [comment]
fixed in v0.1.42
