### ISSUE TITLE
sometimes hotkeys of search and replace doesn't work

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#82]
sometimes have to open the settings first, so the hotkeys of search and replace will work.

**Comment by chiehan1** [comment]
In windows v0.1.42, when using search and replace hotkeys, sometimes it doesn't work, and it will show this 
![search1](https://cloud.githubusercontent.com/assets/13195099/11008203/f8fd9986-8509-11e5-9cc3-f22dd871c025.jpg)

**Comment by kmsheng** [comment]
Please provide information about how to reproduce this issue, thanks.

**Comment by kmsheng** [comment]
@chiehan1 請確認 0.1.64 是否還有此問題 ?

**Comment by chiehan1** [comment]
v0.1.64 沒有這問題，ctrl + f 和 ctrl + shift + f 都可按出搜尋和取代功能
