### ISSUE TITLE
cannot show images when importing zip between mac and windows system

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#84]
In windows version, when I import a zip file which is exported from mac version Ketaka-Lite, it can't show the images, and vice versa. 
![imageinwinmac](https://cloud.githubusercontent.com/assets/13195099/11025546/7287f520-86d7-11e5-90e7-c6beb856afdc.jpg)

**Comment by kmsheng** [comment]
fixed in v0.1.45

**Comment by kmsheng** [comment]
Remember all zips should be generated from this version of KETAKA-Lite to take effect.
