### ISSUE TITLE
toolbar disappear

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#85]
In windows version 0.1.44, (I didn't check mac version yet)
the toolbar will disappear randomly, in win7, win8, win10.
This film is from Khenpo Namgyal (from 00:00:15 to 00:00:20)
https://youtu.be/r8C_AgkxCPQ?t=15s

and this film in win10 system
https://www.youtube.com/watch?v=ZCiAIV3tcqg&feature=youtu.be

and sometimes it will disappear after click the textarea and pagebreak (ctrl + enter),

sometimes it disappears after close search window and replace window.
figures below are in win7 system, the develop toolbar didn't show any error.

the toolbar disappear after closing search window, please see that there is an unusual vary thin line in the orange box 
![toolbardisappear1](https://cloud.githubusercontent.com/assets/13195099/11111453/5cdeecaa-8944-11e5-94af-c7bf4b88d834.jpg)

If I move the mouse cursor on the line, it can show the icon prompt. 
![toolbardisappear2](https://cloud.githubusercontent.com/assets/13195099/11111456/5e4c4236-8944-11e5-9cd7-9ef79bfd453b.jpg)

(change my mouse cursor, it will show different icon prompt just the same position as the toolbar)
![toolbardisappear3](https://cloud.githubusercontent.com/assets/13195099/11111458/6310f618-8944-11e5-8a16-6ba8aca690ae.jpg)

if I open the search window again, or click the line, the toolbar will show.
![toolbardisappear4](https://cloud.githubusercontent.com/assets/13195099/11111463/6604662a-8944-11e5-89f0-1e93cd4a02f5.jpg)

We doubt the thin line is the botton line of the toolbar or the toolbar shrink to a line, or maybe something else.

**Comment by kmsheng** [comment]
I am going to label this issue as "help wanted" because it doesn't provide enough details to reproduce the bug.

**Comment by kmsheng** [comment]
@chiehan1 is this issue the same as #88 ?

**Comment by chiehan1** [comment]
I am not sure if this issue same as #88, please keep this issue open.

**Comment by kmsheng** [comment]
@chiehan1 請確認 0.1.64 是否還有此問題, 我在 win7 測過影片行為
現在已經不會把 toolbar 往上捲了

**Comment by chiehan1** [comment]
0.1.64 好像沒有這個問題了，之後出現的話，能穩定複製此行為的時候我再開 issue
