### ISSUE TITLE
Import GIF and PNG files

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#86]
Hello David:

 @lamalien ask to add importing picture format : GIF and PNG

Thanks!!

**Comment by chiehan1** [comment]
This is the sample file, there are GIF, BMP, PDF(1image/1file, images/1 file), PNG.

https://drive.google.com/file/d/0B7IngcS_Eo5JT1ZyQk9IZnJlZG8/view?usp=sharing

**Comment by kmsheng** [comment]
pdf is not possible unless it's included by an iframe tag which is in conflict with current project architecture.

**Comment by kmsheng** [comment]
applied in v0.1.47
