### ISSUE TITLE
Image area error when importing xml without image

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#87]
In windows v0.1.45 (haven't tried mac yet),
without image, only import xml files with pb tag, the first page will show like this.
There is an icon at the top-left of the image area, the "upload image" button disappear, the last imported xml file name(lj0001-054.xml) is shown as the image name at the bottom-right cornor. 
![importtext](https://cloud.githubusercontent.com/assets/13195099/11142016/5216d27e-8a25-11e5-8872-748db4736a2f.jpg)

**Comment by kmsheng** [comment]
fixed in v0.1.46
