### ISSUE TITLE
toolbar disappear after keeping pressing "enter" until the lines exceed the text area

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#88]
I try this in windows v0.1.45 many times, I am not sure if it's the same problem as #85, so I open a new issue. 
step1 change the direction as the picture below
![1231](https://cloud.githubusercontent.com/assets/13195099/11142833/253a7304-8a2b-11e5-95e1-369dcc1754e9.jpg)
step2 keep pressing "enter" until the lines exceed the text area, the toolbar will disappear, and the image area will become smaller.
![1232](https://cloud.githubusercontent.com/assets/13195099/11142834/27c03884-8a2b-11e5-8af2-7c5925d5068b.jpg)
step3 close ketaka-lite and re-open it, click tab to create a new bamboo, this time the text area become smaller
![1233](https://cloud.githubusercontent.com/assets/13195099/11142836/298bcc82-8a2b-11e5-8f85-4f5a8e91ed94.jpg)
step4 adjust the divided proportion of image area and text area several times, the text area will become normal again 
![1234](https://cloud.githubusercontent.com/assets/13195099/11142840/2c59beec-8a2b-11e5-9466-f8625878080a.jpg)
step5 keep pressing enter in the text area and the toolbar will disappear again
![1235](https://cloud.githubusercontent.com/assets/13195099/11142842/2f787d20-8a2b-11e5-8865-02711d4057ae.jpg)
step6 if I use "ctrl+f", the toolbar will show up, but the botton arrow of the scroll bar disappear. 
![1236](https://cloud.githubusercontent.com/assets/13195099/11143180/481ddcc8-8a2e-11e5-9e91-8bd57f3ce022.jpg)
step7 scroll to the last line, the botton arrow of scroll bar show up,  and click the last line, the toolbar will disappear again.
![1237](https://cloud.githubusercontent.com/assets/13195099/11143183/4a68ab3e-8a2e-11e5-9b34-04549462f941.jpg)

**Comment by kmsheng** [comment]
fixed in v0.1.46
