### ISSUE TITLE
Warn user when import file count is greater than 800

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#89]
Because there is often around 625 images and around 25 xml in a bamboo of jiangkangyur, so @lamalien hope to warn and show the file numbers if the users imported more than 800 files once.

(There are around 1500 images in a bamboo of dengyur. 75kb a image. So it will be 100mb of a bamboo of dengyur. But now we will only focus on the kangyur first.)

**Comment by kmsheng** [comment]
applied in v0.1.47
