### ISSUE TITLE
The cursor focus on the present position after doing other works.

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#90]
Hello David:
This is the situation now.
the cursor is at line3
![cursorposition1](https://cloud.githubusercontent.com/assets/13195099/11144155/a520593a-8a35-11e5-93c0-73376f5d3b92.jpg)
but after doing other works like switch the input method or changing letter spacing or something else on the toolbar or clicking the image area or other place, the cursor doesn't focus on line 3
![cursorposition2](https://cloud.githubusercontent.com/assets/13195099/11144156/a64cffca-8a35-11e5-9d29-3c68f352fcb9.jpg)
the cursor doesn't focus on line 3
![cursorposition3](https://cloud.githubusercontent.com/assets/13195099/11144157/a7901d0e-8a35-11e5-8242-6abbc5b357d7.jpg)

Could you make the cursor stay on where it is after doing other works.
Thank you!!

**Comment by kmsheng** [comment]
applied in v0.1.47
