### ISSUE TITLE
Search or replace from the present cursor postion, not from the beginning of the page.

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#91]
I use the search funtion of emeditor as an example.
the cursor is at the end of line 8
![findcursor1](https://cloud.githubusercontent.com/assets/13195099/11144396/5755596a-8a37-11e5-8c9a-06542365282b.jpg)
and I search "1"
![findcursor2](https://cloud.githubusercontent.com/assets/13195099/11144398/59d08b56-8a37-11e5-836a-43621b2d5d02.jpg)
the "1" in line 9 is double highlight by blue color
![findcursor3](https://cloud.githubusercontent.com/assets/13195099/11144400/5d2a2c44-8a37-11e5-8afa-4919901cca65.jpg)
after search, the cursor is behind the "1" in line 9 and ready to blue-hightlight the next "1"
![findcursor4](https://cloud.githubusercontent.com/assets/13195099/11144402/60c01e04-8a37-11e5-80cd-087bd2155bd0.jpg)

**Comment by chiehan1** [comment]
some supplement here

Khenpo Namgyal don't want the present position go back to the beginning of the text after calling the search window and replace window.
Now the Ketaka-Lite is as the screenshot below:
figure1. The cursor is at line 18
![findrepacecursor1](https://cloud.githubusercontent.com/assets/13195099/11167074/38d07bb6-8b8e-11e5-940f-778bee1b3bd0.jpg)
figure2. The position go back to the first line after the search window showing.
![findrepacecursor2](https://cloud.githubusercontent.com/assets/13195099/11167075/3b74183c-8b8e-11e5-8424-49b21ad0d339.jpg)
Khenpo Namgyal hopes the position will stay in the present place just like before calling the search window and replace window.
Thank you so much!

**Comment by kmsheng** [comment]
applied in v0.1.47

**Comment by chiehan1** [comment]
Dear David:  

I have to apologize that I didn't write it very clearly in the title and the comments.
When users replace one-by-one, it replaces from the cursor positions, and when replacing next word, the cursor and the text will jump to the next target.(取代下一個時，游標和文字畫面都會移動到該字，像現在的版本一樣) 
but when users replace all, all matched words from the beginning of the text should be replaced, but the cursor and the text (只替換從頭到尾所有符合的字元而已, 但是游標和文字畫面都不移動) will still stay at the position which is before replacing, not jump to the beginning.
I am pretty much sure this is how the example worked in Khenpo Namgyal's video.
Could you please help fix it, we will all very appreciate that!! Thank you so much!! 

Chieh An

**Comment by chiehan1** [comment]
列一下規則
1. 使用搜尋功能或取代功能時，會算出整個bamboo的符合數，所有符合的字都會被highlight(目前在default theme是淡藍色)
2. 使用搜尋或取代功能時，游標和頁面會先停留在當前位置，不會跳回最前面(真抱歉，我的標題的意思其實是這句，造成混淆，真不好意思)，當搜尋上一個字或搜尋下一個字，或一個一個取代時，會以當前的游標位置為起點跳到當前游標的上一個或下一個被搜尋的字或下一個將被取代的字，而頁面也跟著跳到這個字的所在段落，同時這個字會加上不同的highlight顏色(目前在 default theme是灰色)，這時其他符合的字一樣是淡藍色highlight
3. 取代全部時，整個bamboo符合的字都會被取代，會算出這一步所取代的總數，但是這時游標和頁面仍然在當前位置。

**Comment by kmsheng** [comment]
@chiehan1 Please try v0.1.56

**Comment by kmsheng** [comment]
@chiehan1  目前版本已經到 v0.1.62, 請捷安確認此票狀況是否還存在

**Comment by chiehan1** [comment]
感謝！
在 mac 中，游標在第二行的 1 前面
![1](https://cloud.githubusercontent.com/assets/13195099/13631414/806cfab2-e61f-11e5-8f4c-6501f6592401.png)
叫出搜尋或取代功能後，輸入1
應該highlight 第二行的1
但目前會跳下一個去highlight到第三行的1
![2](https://cloud.githubusercontent.com/assets/13195099/13631420/86dd7b9c-e61f-11e5-9721-113a9af8ea0b.png)

**Comment by chiehan1** [comment]
承接上一個comment
在mac和windows系統中
一直按取代的快捷鍵 control shift f
highlight 不會往下一個一個跳
而是往下跳兩個

![2016-03-09 6 07 44](https://cloud.githubusercontent.com/assets/13195099/13632014/97cd634c-e622-11e5-8fce-287e2d4522ac.png)
![2016-03-09 6 10 03](https://cloud.githubusercontent.com/assets/13195099/13632018/9d88f3f0-e622-11e5-90ce-472b2b8a4878.png)
![2016-03-09 6 10 17](https://cloud.githubusercontent.com/assets/13195099/13632022/a2047508-e622-11e5-93e8-4488cb70c870.png)

**Comment by kmsheng** [comment]
@chiehan1 fixed in 0.1.64

**Comment by kmsheng** [comment]
捷安明天請假, 轉給志軒檢查

**Comment by chiehan1** [comment]
感謝
v0.1.66
cursor 位置在打開搜尋和取代功能時，不要跳回頁面開頭的需求，此 issue 已解決

**Comment by chiehan1** [comment]
照2016/3/3 開會決定勘布其他有關搜尋和取代的需求先不優先處理
comment 提到的按 control shift f 的 cursor 跳動問題，目前已經改成定住 cursor 不動
此 issue 的 cursor 位置還有一個問題，另外開 issue，不然太亂
所以關掉此 issue
