### ISSUE TITLE
Show the matched number after searching and before replacing, and show replaced number after replacing

### ISSUE THREAD

**Issue by chiehan1** [karmapa/ketaka-lite#92]
Hello, David:

Khenpo Namgyal hopes that Ketaka-Lite can show 
1. the matched number after searching,  
2. before replacing, 
3. replaced number after replacing
maybe in the botton-left of the text area or any other place you think better than botton-left of the text area. 

Thank you so much!!

**Comment by kmsheng** [comment]
fixed in v0.1.48
