### ISSUE TITLE
Import 資料後，很多文字那一頁，中間行數欄位會變寬。 pagebreak後，會變回正常。

### ISSUE THREAD

**Issue by lamalien** [karmapa/ketaka-lite#97]
1.  Import 資料後，很多文字那一頁，中間行數欄位會變寬。 pagebreak後，會變回正常。
   <befor pb break>
   ![issue_16112015_1a](https://cloud.githubusercontent.com/assets/5266492/11183512/1667dab8-8cad-11e5-9296-30e3f65a1ae0.png
   <after pb break>
   ![issue_1611201_1b](https://cloud.githubusercontent.com/assets/5266492/11183517/1da9c9bc-8cad-11e5-8b60-a4477a893a56.png)
   <beforr pb break>
   ![issue_16112015_1c](https://cloud.githubusercontent.com/assets/5266492/11183521/25328688-8cad-11e5-9fcc-881755a113d9.png)
   <after pb break>
   ![issue_16112015_1d](https://cloud.githubusercontent.com/assets/5266492/11183526/2ba74a30-8cad-11e5-9c77-b051859ae648.png)

**Comment by kmsheng** [comment]
@lamalien 這是 codemirror 設定的行為, 假設你的螢幕解析度很窄, 又一直沒有遇到換行符號 codemirror 就會幫你換行, 但是行數還是顯示同一行。

如果不這樣設的話, 過長的文字就會出現橫向捲軸了, 很不方便。
