### ISSUE TITLE
1.	Import 資料後，很多文字那一頁，中間行數欄位會變寬。 pagebreak後，會變回正常。

### ISSUE THREAD

**Issue by lamalien** [karmapa/ketaka-lite#98]
1.  Import 資料後，很多文字那一頁，中間行數欄位會變寬。 pagebreak後，會變回正常。
   <befor pb break>

![issue_16112015_1a](https://cloud.githubusercontent.com/assets/5266492/11183636/ebfa7ae6-8cad-11e5-8132-b74ad86ede95.png)

<after pb break>
![issue_1611201_1b](https://cloud.githubusercontent.com/assets/5266492/11183517/1da9c9bc-8cad-11e5-8b60-a4477a893a56.png)
<beforr pb break>
![issue_16112015_1c](https://cloud.githubusercontent.com/assets/5266492/11183521/25328688-8cad-11e5-9fcc-881755a113d9.png)
<after pb break>
![issue_16112015_1d](https://cloud.githubusercontent.com/assets/5266492/11183526/2ba74a30-8cad-11e5-9c77-b051859ae648.png)

**Comment by kmsheng** [comment]
法海師你這個跟 #97 重複了, 先幫你關掉
