### ISSUE TITLE
分別執行下列a-d動作後，有 視窗變成像剛進入KERAKA LITE的情況。 新增分頁的框框(App下面的小框框)消失，不能執行其他動作。 重開KERAKA 才能open檔案。  a.編輯文字→APP→SAVE→跳掉。(NO SAVE) b.DOC NAME→SAVE AND CLOSE→跳掉。(SAVE) c.編輯文字→PAGEBREAK→按下一頁→跳掉。 d.編輯文字→PAGEBREAK→看不見最後一行→SAVE→跳掉→toggle developer tools

### ISSUE THREAD

**Issue by lamalien** [karmapa/ketaka-lite#99]
1.  分別執行下列a-d動作後,有 視窗變成像剛進入KERAKA LITE的情況。 新增分頁的框框(App下面的小框框)消失，不能執行其他動作。 重開KERAKA 才能open檔案。  a.編輯文字→APP→SAVE→跳掉。(NO SAVE) b.DOC NAME→SAVE AND CLOSE→跳掉。(SAVE) c.編輯文字→PAGEBREAK→按下一頁→跳掉。 d.編輯文字→PAGEBREAK→看不見最後一行→SAVE→跳掉→toggle developer tools
   ![issue_16112015_2a](https://cloud.githubusercontent.com/assets/5266492/11183821/d438c628-8cae-11e5-9ca8-10ecda4a4aba.png)
   ![issue_16112015_2b](https://cloud.githubusercontent.com/assets/5266492/11183820/d4381da4-8cae-11e5-95cd-1af9f0bd731a.png)

**Comment by kmsheng** [comment]
@lamalien 抱歉, 看不太懂這個 issue 想要表達的問題是什麼 ? ( developer tools 不給一般使用者用的 )

**Comment by kmsheng** [comment]
@lamalien 另外, 請不要把 title 欄位當 description 欄位用, 感謝。

**Comment by kmsheng** [comment]
![screen shot 2015-12-02 at 5 08 04 pm](https://cloud.githubusercontent.com/assets/880569/11526698/4824160e-9917-11e5-9ca8-09ad52b547b1.png)
